<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pune</name>
   <tag></tag>
   <elementGuidId>ece0f2c3-200b-4d78-908a-cffa95d4f7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-omni-suggestion-item__content__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-omni-container']/div/div/div[2]/div[2]/div/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^Pune$/ >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b5a2d32-c724-4764-8b3a-e3c700cfda34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-suggestion-main</value>
      <webElementGuid>32fc6584-5893-448f-8b91-c06d1e9c16db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-suggestion-item__content__title</value>
      <webElementGuid>be5d44e1-859f-4942-94a6-206db0b9a776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pune</value>
      <webElementGuid>8a08d5c2-ad3b-4b9e-b1f3-c3be622361ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--locality&quot;]/div[@class=&quot;c-omni-suggestion-list&quot;]/div[@class=&quot;c-omni-suggestion-group&quot;]/div[@class=&quot;c-omni-suggestion-item&quot;]/span[@class=&quot;c-omni-suggestion-item__content&quot;]/div[@class=&quot;c-omni-suggestion-item__content__title&quot;]</value>
      <webElementGuid>1da7d3a1-2d39-4c08-8162-f6cbad9e28a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div/div[2]/div[2]/div/span/div</value>
      <webElementGuid>4294ad53-530a-40da-8f50-84d3056dfda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use my location'])[1]/following::div[5]</value>
      <webElementGuid>0636008a-7d2e-4c1a-9659-b92f5d507933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find and Book'])[1]/following::div[15]</value>
      <webElementGuid>8b7f9cfc-7562-488b-ba8c-7dcf6e2b53fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITY'])[1]/preceding::div[1]</value>
      <webElementGuid>fe87b573-b186-448e-a992-0ba52b20219c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puneet Nagar'])[1]/preceding::div[3]</value>
      <webElementGuid>1c72cd97-b0db-48b1-be5f-dbcca6c4e71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pune']/parent::*</value>
      <webElementGuid>38a30ffa-07f7-4346-b51c-2103658945e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div</value>
      <webElementGuid>d9d8b789-1268-4198-8df3-796b095223df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pune' or . = 'Pune')]</value>
      <webElementGuid>697e3b3e-5266-44ae-8b7c-c264a0224ee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
