<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Baner</name>
   <tag></tag>
   <elementGuidId>35e4fa86-2c63-42f0-ad3e-a6e70ef0aa0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-omni-suggestion-item__content__sub_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-omni-container']/div/div[2]/div[2]/div/div[2]/span/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Baner&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>afccb55d-eabf-4905-878e-5174c1509708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-suggestion-subtext</value>
      <webElementGuid>55a4f23a-5a55-4c22-bed2-72800737742f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-suggestion-item__content__sub_text</value>
      <webElementGuid>6a3a0782-2991-473b-9a24-b0cf826c915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baner</value>
      <webElementGuid>80eabf72-79ff-4d13-a442-9ac152f4df2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--keyword&quot;]/div[@class=&quot;c-omni-suggestion-list&quot;]/div[@class=&quot;c-omni-suggestion-group&quot;]/div[@class=&quot;c-omni-suggestion-item&quot;]/span[@class=&quot;c-omni-suggestion-item__content&quot;]/div[@class=&quot;c-omni-suggestion-item__content__sub_text&quot;]</value>
      <webElementGuid>d0668e62-6f70-408b-886b-ac2295808060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div[2]/div[2]/div/div[2]/span/div[2]</value>
      <webElementGuid>61314233-3af7-4fe9-aeec-8f652cb46dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jupiter Hospital'])[1]/following::div[1]</value>
      <webElementGuid>5378998d-32f9-41a3-8170-a91b82a18450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospitals'])[1]/following::div[5]</value>
      <webElementGuid>c036ae95-69ae-4754-884a-4a049139f365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinics'])[1]/preceding::div[1]</value>
      <webElementGuid>82f7ba7b-6135-4fcb-80e9-ee5e996fc51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J'])[1]/preceding::div[2]</value>
      <webElementGuid>a597fdb3-a9a6-484e-b957-84b553642a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baner']/parent::*</value>
      <webElementGuid>7c5264ab-ed58-41b8-8560-b92eaca7d583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[2]</value>
      <webElementGuid>c99a5dc1-2e66-4fe2-95eb-f364b6bd2dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Baner' or . = 'Baner')]</value>
      <webElementGuid>12f1ae7e-3422-49e9-815c-f546232b4ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
