<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find and Book_c-omni-searchbox c-omni_58efd4_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21</name>
   <tag></tag>
   <elementGuidId>737c7c5b-c4f7-4384-8c0c-76800aa1bec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-omni__wrapper.u-clearfix.c-omni__wrapper--keyword > div.c-omni-searchbox_wrapper > input.c-omni-searchbox.c-omni-searchbox--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Jupiter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search doctors, clinics, hospitals, etc.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1905a3e7-62b6-4fc7-a83a-063f53e7e96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-searchbox-keyword</value>
      <webElementGuid>bfdde518-88bc-44ae-98d6-5602c53500f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-box-id</name>
      <type>Main</type>
      <value>omni-searchbox-keyword</value>
      <webElementGuid>ba944fb1-d7c7-4af2-b5f4-e635a928c964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-searchbox c-omni-searchbox--large</value>
      <webElementGuid>b83bd06a-60dd-491f-a82f-cf9552b481c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a3109cf1-bd47-4ee3-956c-9019c3f260f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search doctors, clinics, hospitals, etc.</value>
      <webElementGuid>ae702227-f0df-424c-8aee-4ce58490ecf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Jupiter</value>
      <webElementGuid>70ded74b-d3fd-412a-8774-d596829fc115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--keyword&quot;]/div[@class=&quot;c-omni-searchbox_wrapper&quot;]/input[@class=&quot;c-omni-searchbox c-omni-searchbox--large&quot;]</value>
      <webElementGuid>781ee8a3-b992-4b7e-aa9a-385564697407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Jupiter']</value>
      <webElementGuid>0f812dcd-0843-4441-bb12-7742d5217281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div[2]/div/input</value>
      <webElementGuid>d94688fd-9a99-45e9-82a8-81bbe98c8a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>14613d91-8002-407a-be72-9a51707fe4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search doctors, clinics, hospitals, etc.']</value>
      <webElementGuid>c0ddbb46-ec78-4039-b824-885512a9ce16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
