<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find and Book_c-omni-searchbox c-omni_58efd4_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>730b2a64-6840-4bf0-84b2-5311f7fc7a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.c-omni-searchbox.c-omni-searchbox--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Banga']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search location&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c76eb3bf-94c7-4b9a-9b52-52ac2340cd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-searchbox-locality</value>
      <webElementGuid>cc0bbb17-9ad3-44d7-be85-c0e824ff1d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-box-id</name>
      <type>Main</type>
      <value>omni-searchbox-locality</value>
      <webElementGuid>bd1f9410-28a6-436d-b173-c611b7f49219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-searchbox c-omni-searchbox--large</value>
      <webElementGuid>123d67c3-f60a-472c-a63f-f0328283cc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>76ea754c-80f3-48e5-99d1-43f588563fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search location</value>
      <webElementGuid>129dabe6-9062-4098-b190-2ba87b42de67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Banga</value>
      <webElementGuid>93bc4638-569b-4119-b339-520c834d6e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--locality&quot;]/div[@class=&quot;c-omni-searchbox_wrapper&quot;]/input[@class=&quot;c-omni-searchbox c-omni-searchbox--large&quot;]</value>
      <webElementGuid>315c6d06-6b4b-417e-889c-ecb057df2a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Banga']</value>
      <webElementGuid>fd9f6e6c-01ce-42ba-ba7d-264e67a2d1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div/div/input</value>
      <webElementGuid>cf3e6283-2a66-4e5d-94b1-5205f52c4aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>75d61587-79fd-4912-b406-a0b6f75ead4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search location']</value>
      <webElementGuid>c12dfa74-3b48-47fc-ad2a-8e964e28b522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
