<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find and Book_c-omni-searchbox c-omni_58efd4_1_2_3_4_5_6_7_8_9_10_11_12_13</name>
   <tag></tag>
   <elementGuidId>9d10cba9-c481-4fa0-aed5-1167cc523c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.c-omni-searchbox.c-omni-searchbox--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Pune']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search location&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18e45e62-ea4b-43e0-873f-550f80269bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-searchbox-locality</value>
      <webElementGuid>de7c496b-f91d-4035-b001-bd02e623be9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-box-id</name>
      <type>Main</type>
      <value>omni-searchbox-locality</value>
      <webElementGuid>161be1cb-3108-4863-aa19-d2dffcff487a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-searchbox c-omni-searchbox--large</value>
      <webElementGuid>b06687c4-f45c-4037-b4f5-65ea52964fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9658aac-5442-49be-aafe-a52cd79056d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search location</value>
      <webElementGuid>62b703dc-0e98-4e18-b33c-d5836d31a194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pune</value>
      <webElementGuid>c3e6d2e8-ec16-4d68-b96f-66a346567e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--locality&quot;]/div[@class=&quot;c-omni-searchbox_wrapper&quot;]/input[@class=&quot;c-omni-searchbox c-omni-searchbox--large&quot;]</value>
      <webElementGuid>5f37f3af-b113-4c3d-a32b-3def07d5f62b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Pune']</value>
      <webElementGuid>7cff4ba9-c310-455a-81a7-896cef281a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div/div/input</value>
      <webElementGuid>564b5f6a-c673-46cd-9f0d-550d2763e9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7d730e7e-a2a1-4095-aff7-dc2cc4ec606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search location']</value>
      <webElementGuid>bdcbd949-136f-4f9e-bc1e-6ed1fbd9698c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
