<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find and Book_c-omni-searchbox c-omni_58efd4_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20</name>
   <tag></tag>
   <elementGuidId>b8b7ee21-3ac5-4e2b-8af0-ba1f9ca64004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-omni__wrapper.u-clearfix.c-omni__wrapper--keyword > div.c-omni-searchbox_wrapper > input.c-omni-searchbox.c-omni-searchbox--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Jupite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search doctors, clinics, hospitals, etc.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae3c9545-3e6d-408e-a84d-bc0cfc2e82df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-searchbox-keyword</value>
      <webElementGuid>59ca777e-5d2a-4058-a207-7843bef41bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-box-id</name>
      <type>Main</type>
      <value>omni-searchbox-keyword</value>
      <webElementGuid>5d5bea94-5016-4132-ba9c-25504cfffff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-searchbox c-omni-searchbox--large</value>
      <webElementGuid>e8a13d7e-7b86-4af6-9642-95a0f3395b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dec0652a-ecc2-4b4b-8e3c-885db5344c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search doctors, clinics, hospitals, etc.</value>
      <webElementGuid>25252f1a-e7d7-4155-b8c2-8da5c1ed7c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Jupite</value>
      <webElementGuid>6a18158c-a4fa-44eb-b202-dca956c94519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--keyword&quot;]/div[@class=&quot;c-omni-searchbox_wrapper&quot;]/input[@class=&quot;c-omni-searchbox c-omni-searchbox--large&quot;]</value>
      <webElementGuid>ccbd76c0-5d45-41a1-b66d-2c50a9faa936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Jupite']</value>
      <webElementGuid>d4fef9e2-df39-4c33-ae54-bc8fbc2c6b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div[2]/div/input</value>
      <webElementGuid>2f2bee2b-30e8-49dd-9515-2ff717a81aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fccb789c-27ff-4302-bae8-65e2225ed173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search doctors, clinics, hospitals, etc.']</value>
      <webElementGuid>51b0f53c-7bcd-4491-8e4e-7a0e3d12aa0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
