<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find and Book_c-omni-searchbox c-omni_58efd4_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19</name>
   <tag></tag>
   <elementGuidId>04cad767-43e3-47d7-95b2-68813364ea7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-omni__wrapper.u-clearfix.c-omni__wrapper--keyword > div.c-omni-searchbox_wrapper > input.c-omni-searchbox.c-omni-searchbox--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Jupitr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search doctors, clinics, hospitals, etc.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ef3cbaa-f155-412a-b5d4-421a722db32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-searchbox-keyword</value>
      <webElementGuid>1974813c-9800-4904-bdc7-2652c4117953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-box-id</name>
      <type>Main</type>
      <value>omni-searchbox-keyword</value>
      <webElementGuid>a3d90fac-249a-4da4-8d5b-51b6ec4ee7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-searchbox c-omni-searchbox--large</value>
      <webElementGuid>861c7fcc-6470-46f7-9744-71c49081e80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea8d2f5e-f08a-481e-beb2-d7e816b4a2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search doctors, clinics, hospitals, etc.</value>
      <webElementGuid>79157eb6-8b04-4fab-8cfa-022df6e698aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Jupitr</value>
      <webElementGuid>c5915294-5adc-4919-a001-47e290afe148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--keyword&quot;]/div[@class=&quot;c-omni-searchbox_wrapper&quot;]/input[@class=&quot;c-omni-searchbox c-omni-searchbox--large&quot;]</value>
      <webElementGuid>675dd3ea-6d0f-4b98-9928-81b94b258305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Jupitr']</value>
      <webElementGuid>591ccd92-6734-438e-94d3-3467f7c8e1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div[2]/div/input</value>
      <webElementGuid>e6e677df-ccce-4ec8-9c68-c8c01d5e6295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1bdb7759-c8c8-49da-8b42-7cb5a626c0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search doctors, clinics, hospitals, etc.']</value>
      <webElementGuid>fb729aa8-c630-4d5a-a37b-7c84c15b3087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
