<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Got it_hamburgerMenu</name>
   <tag></tag>
   <elementGuidId>dce6d039-c4df-4b32-a2a4-879df4731326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp']/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.hamburgerMenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.hamburgerMenu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>affb5dd7-2e19-4c58-9654-4cb062f2828c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburgerMenu</value>
      <webElementGuid>e44f0d55-639f-4a90-b654-74de73343f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp&quot;)/div[@class=&quot;gfgheader_parentContainer&quot;]/div[1]/div[@class=&quot;topBar&quot;]/span[@class=&quot;hamburgerMenu&quot;]</value>
      <webElementGuid>b0f3fdfe-91d8-4e99-be91-a49328f80608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp']/div/div/div/span</value>
      <webElementGuid>ab25e960-eb92-4caf-90f0-c7452f8e5ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got it!'])[1]/following::span[1]</value>
      <webElementGuid>0c1193f8-0fa6-4022-8198-07fde3295011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Structure'])[1]/preceding::span[5]</value>
      <webElementGuid>54308570-829a-4f78-9b54-f6e5f7671485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[1]/preceding::span[6]</value>
      <webElementGuid>40ed3071-498a-4663-aa15-9fd0c3b697cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>8688b801-dc42-441c-aa04-3aa35ed39822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
