<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_30</name>
   <tag></tag>
   <elementGuidId>c5b8326f-03fd-4858-b2bf-a832ea9772de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sizeButtonsContainer']/div[2]/div[3]/div/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;30&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d32d4f00-140c-49c8-a3e5-cdc9502abc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-buttons-unified-size</value>
      <webElementGuid>fc7439af-9aa7-4b48-955c-c1914e55f9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>cd98d411-fa71-4758-9749-946a24408835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sizeButtonsContainer&quot;)/div[@class=&quot;size-buttons-size-buttons&quot;]/div[@class=&quot;size-buttons-tipAndBtnContainer&quot;]/div[@class=&quot;size-buttons-buttonContainer&quot;]/button[@class=&quot;size-buttons-size-button size-buttons-size-button-default&quot;]/p[@class=&quot;size-buttons-unified-size&quot;]</value>
      <webElementGuid>582afee5-b0e2-474e-b33b-b2cd8d970db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sizeButtonsContainer']/div[2]/div[3]/div/button/p</value>
      <webElementGuid>cd4d75b9-bed5-4c6f-94d9-29fbeaed5061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Fit Waist - 28.0in'])[1]/following::p[1]</value>
      <webElementGuid>8c51eb63-ca78-4b28-9183-25024ce5f13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide'])[3]/preceding::p[1]</value>
      <webElementGuid>c71284ec-5150-4c11-bc9a-af9a3aba966e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Measurement:'])[3]/preceding::p[1]</value>
      <webElementGuid>5edc2b82-22bf-46d1-8709-a40bef870456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30']/parent::*</value>
      <webElementGuid>8a80bb92-29b1-42a1-ba67-c2611a90a84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/p</value>
      <webElementGuid>5a6705e3-153e-4931-8989-579a112e0ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '30' or . = '30')]</value>
      <webElementGuid>5758b191-eed2-45ec-960d-b7aed9ad93a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
