<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bag</name>
   <tag></tag>
   <elementGuidId>3d1431d6-924f-4245-8464-119116955696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.desktop-cart > span.desktop-userTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/a[2]/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1 Bag&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>abfc1137-d0e5-40e3-8439-6e58fec94215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-userTitle</value>
      <webElementGuid>e2d547b4-b96f-45f2-a59c-dec7d236102b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>872</value>
      <webElementGuid>53eccb2a-4412-42f6-9735-9d9c1919c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bag</value>
      <webElementGuid>0f42f81d-b100-4b84-a07e-8f842cc65627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-actions&quot;]/a[@class=&quot;desktop-cart&quot;]/span[@class=&quot;desktop-userTitle&quot;]</value>
      <webElementGuid>bed10b39-eb83-458d-9407-5d60276ee737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/a[2]/span[3]</value>
      <webElementGuid>5c30668a-8fa1-4eec-a049-08b089c26b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[2]/following::span[3]</value>
      <webElementGuid>640b0cde-209a-4123-81c9-fe6250414ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved Addresses'])[1]/following::span[5]</value>
      <webElementGuid>27c31495-5d47-4bda-8f78-89e9eed0e108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bag']/parent::*</value>
      <webElementGuid>1644633c-1040-4efc-b570-daaa0f88edca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>7e687197-4f80-4d5d-a60b-3bd007a00491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bag' or . = 'Bag')]</value>
      <webElementGuid>ae3aa5ea-0341-4d40-8bd1-40cde5439698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
