<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We spark action with our audience</name>
   <tag></tag>
   <elementGuidId>e6f10595-5555-4630-9b45-211013169975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp']/div[2]/div[3]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.aboutUs_head_left--descText__cqTof</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;We spark action with our audience.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53349b10-155e-4bec-b9ff-3dc5e6f59f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aboutUs_head_left--descText__cqTof</value>
      <webElementGuid>2d088f8b-d0a5-49f8-bc2b-c21055238b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We spark action with our audience.</value>
      <webElementGuid>87f12a81-ab7d-4950-b1a9-828c84d84b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-mode&quot;)/div[@id=&quot;comp&quot;]/div[@class=&quot;advertise-with-us_head__skUPZ&quot;]/div[@class=&quot;aboutUs_head__Ywchk&quot;]/div[@class=&quot;aboutUs_head_left__2w_ex&quot;]/div[@class=&quot;aboutUs_head_left--descText__cqTof&quot;]</value>
      <webElementGuid>acd2429f-3860-45ba-9b6d-f649a7179ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp']/div[2]/div[3]/div/div[2]</value>
      <webElementGuid>bd62aa58-002a-4ecb-8b56-26215d6e4dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::div[2]</value>
      <webElementGuid>76020aa4-8733-4b35-957d-a69ab7c77279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate lead with 20 million+ Logged in users'])[1]/following::div[6]</value>
      <webElementGuid>c88217e8-fdbf-4a2b-88fe-ab146f600a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expertise that everybody counts on'])[1]/preceding::div[1]</value>
      <webElementGuid>d1675574-e301-4519-963c-06398e305441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stay Ahead with Our Recurring Events'])[1]/preceding::div[4]</value>
      <webElementGuid>2b3a193f-6ef2-4720-9691-21b83ae19af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We spark action with our audience.']/parent::*</value>
      <webElementGuid>84a65e3b-1e19-41e5-b72b-0104b6b0a71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>18414364-65cb-47da-95eb-e8fb2a194dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'We spark action with our audience.' or . = 'We spark action with our audience.')]</value>
      <webElementGuid>6c2c4565-ab67-429a-b203-4844a2e696a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
