<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send OTP</name>
   <tag></tag>
   <elementGuidId>ffdb48db-9b02-4f11-81e9-a2d4f30ac205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='EmailRegister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Send OTP&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f922f248-7653-4eae-a3b0-512251da9622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn  btn-lg common-btn practo-btn</value>
      <webElementGuid>b9717da3-488f-4c75-be11-a383d6fb72b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailRegister</value>
      <webElementGuid>2ce4ed21-81bd-40d1-b8cf-a39cccc11442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send OTP</value>
      <webElementGuid>96a9d7b8-7a4a-4de5-b655-1e3cbbb544d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailRegister&quot;)</value>
      <webElementGuid>9e94a012-c176-4366-a7d1-df8614f44f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='EmailRegister']</value>
      <webElementGuid>3b8d5582-3b89-4008-aa52-2a8fd53b223e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register_email_form']/div/div[2]/div[6]/div[3]/button</value>
      <webElementGuid>f8e5eae8-9f03-4eeb-96cc-0356cd3881ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='terms'])[1]/following::button[1]</value>
      <webElementGuid>8658ae98-68b9-4674-ace5-4fe526d116f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive relevant offers and promotional communication from Practo'])[1]/following::button[1]</value>
      <webElementGuid>eab2796b-3fb5-4099-ba2f-91a859dd27c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practo'])[2]/preceding::button[1]</value>
      <webElementGuid>f3b3080d-7e43-44f7-8338-e8db08166a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::button[1]</value>
      <webElementGuid>544a3ed3-9c7d-4509-9c5f-d232cf75e1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send OTP']/parent::*</value>
      <webElementGuid>84d5b4b9-179e-4c2e-b988-ebec660708d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>99368757-2c20-4f19-8136-dafb165f3e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'EmailRegister' and (text() = 'Send OTP' or . = 'Send OTP')]</value>
      <webElementGuid>8f889395-7f66-4980-83f1-1178e9595e35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
