<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</name>
   <tag></tag>
   <elementGuidId>492a2265-e990-44a2-b6b7-230fee884aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-h0ceivc4gms3&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-h0ceivc4gms3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-h0ceivc4gms3&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4419b558-f30f-4ad6-a7ab-ec013b77aee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>3cc26822-3ea3-4fde-951b-ddb1c1672fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-h0ceivc4gms3</value>
      <webElementGuid>9ec3d92f-93ea-4eef-840e-d2e4aa7d4923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63f2a000-b169-439e-bc58-ea708465611c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>74a19d48-a7ac-40d9-958a-b62b81238aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>8cd04a17-ded1-4503-8de5-d60575e1b3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=rW64dpMGAGrjU7JJQr9xxPl8&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>eb7dffd7-1fd9-4e70-981c-75a116792013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[2]/iframe[1]</value>
      <webElementGuid>102f841f-8f95-4852-bf22-2d29897eb7be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-h0ceivc4gms3']</value>
      <webElementGuid>b4bc2368-1d7d-422b-b10a-d191a9c2dde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>ed1d02dc-6839-4242-badc-023020253427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-h0ceivc4gms3' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=rW64dpMGAGrjU7JJQr9xxPl8&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>04d98858-b7de-40e3-9325-81bb9f28e4b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
