<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>ee93f649-074c-4d99-a4ec-afa736e39048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ff44366-5d94-44a2-817a-43c4446fd658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>11aa787c-6556-4922-bb19-de67cee3d2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>9158a1e0-7fb6-4cb4-b827-c881504395f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>79fdb23f-2a11-4f55-bdae-4931cef195d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>7694f148-2825-4041-bc4e-140c5b743cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>7dbf0a87-80c7-4ca1-ac6c-c3e03beffd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[2]</value>
      <webElementGuid>169bba1e-b35a-454d-9d28-00b905044a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>f98e7bfb-7b15-41c8-af51-ca91cdbfc067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>0565321a-e535-42d5-afcb-1c9938a769f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
