<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_boats_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>8c5873ff-fce6-4091-815e-33ad773c3593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0f85279a-0356-42ae-8cf2-4f45e3c69fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>776fdf1a-1de5-49db-b16f-3d10e5b54564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>af233f64-5bb0-4e4f-b591-2f3e13bef8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>a4d77bfc-51b5-4a96-a03b-c4269ab33338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>3d493711-82e5-4d24-8eff-54a62d38afcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>453433b7-048b-4b0f-987c-141fdd721c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[8]</value>
      <webElementGuid>72cf9d84-f891-4d7c-ac99-dc0a1e8c9b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>69e98fca-ef8f-4d4e-b338-617bd0c4615b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>5ca38ab4-a1ab-4745-8de7-ca14e060d108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
