<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>ac5cea6f-2c14-44d5-a126-4692bfe626f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da9bb7f1-c1f1-47d7-934f-a42706f9c715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>47c8f295-e7f6-442f-9964-f35ac8cc4860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>a72de152-f471-4686-aae9-5b6480933606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>b1c73506-b24d-4013-bc92-e037ed5648ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>124870f2-7041-4d30-bd90-f7cd048788dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>cab84969-a482-47fb-9270-084f3b89bc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[4]</value>
      <webElementGuid>c031e952-c2de-4b01-9248-ad8822d91446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>dc650b78-0d3c-4ded-bbd5-e23cce297c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>8c9111c9-4e32-4713-aa52-2fefa8387c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
