<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_boats_rc-image-tile-33_1_2_3</name>
   <tag></tag>
   <elementGuidId>093a2ef9-c68f-44c8-a150-f026cced164c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a13314f8-22bd-48c4-b433-102eefc33eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>648de937-89c3-4e11-8eb3-54f3a9971b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>6ba9e1d2-f17c-4e9a-9e79-8060f0670ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>92a0e094-6c9c-487a-880d-62dd039713b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>0a8bd7f7-f298-4486-a44a-0d3c34ca913f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>d3bd1b34-ddc7-483f-97df-b62068207265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')]</value>
      <webElementGuid>da559488-b98b-4e6d-a28b-88f139e8ee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bd731640-3d7f-4a75-a762-b07cbbf81598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>1a2ed95c-ea9b-468d-a826-4231c6533040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
