<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3</name>
   <tag></tag>
   <elementGuidId>797dc8b5-d6c1-4670-bb81-9ecea0347796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d888c100-f1d0-4125-a601-e991ca98e9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>d063618c-bf2f-46e4-80ee-93433170d3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>56807c4d-d121-49de-b865-978aaea4f54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>2e98d3f9-3e04-4e1c-b2fc-4414d90d8bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>bf63ab77-15f5-4245-a891-5361f161fa28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>80155793-9bdf-4730-8dab-c8511968a9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[4]</value>
      <webElementGuid>6de98dbc-9c35-4376-83c9-9cc299475d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>342fb6a7-aff5-47af-83e7-bce8092183be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>c36c9bd5-851a-4936-a77e-1a16a39a0d7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
