<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-33_1</name>
   <tag></tag>
   <elementGuidId>b18af8b5-0368-4219-826d-7372fda1fbae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fde01562-d644-46ba-91c4-35bf4c10b82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>6244b575-1dc0-4cb4-9813-36d67a5d9fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>205c5457-97c9-4794-8600-9ca298baa3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>4a43c388-b805-461e-8277-7f2a2f95699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>4840e573-a168-430c-8edb-7f57d4465b20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>1cebbf74-bf8e-4345-9a79-030ebda17b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[5]</value>
      <webElementGuid>02ea5d32-7459-47c3-af0d-45a5c3336edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>3522756b-fd5a-4b30-a315-6e8d1a929af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>f5207b1f-ba78-43fd-a904-9aae94d2621b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
