<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_boats_rc-image-tile-33_1</name>
   <tag></tag>
   <elementGuidId>985ceb5c-eca0-42ea-9ab7-088cdbfcf3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dabfad99-c6fc-4aaf-8e1b-9a3db6cd0adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>ba9be007-db1e-482c-8584-f502c726dc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>e67362f1-5337-4d96-8eb7-4e68d78fe623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>d80cc859-6b51-4d22-bc53-d4d7543d53f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>ffdae210-c948-459f-b029-62fe28befd68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>eeedb329-ae32-4364-ae56-e23b2db1350e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[9]</value>
      <webElementGuid>1f64c749-c68d-4b57-892c-788ffbbdec0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>2904201a-3e05-4d0a-aeb0-195eb74be808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>bcab9592-8588-4061-ab54-26a6bbb525a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
