<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-33_1_2</name>
   <tag></tag>
   <elementGuidId>987bf4b7-4248-48a8-83dc-8c7991209481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0703c7cd-f568-4eab-8860-6de060aab155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>948ee711-8768-4315-bd40-044d12b5baf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>adce7d5e-5e6f-4d32-8572-2e23b962439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>637a710e-b5c2-40d9-9b9c-c80770224519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>871d3c1f-95e2-447f-a005-e7b3e4bdb66f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>cd887c1e-c382-4556-9009-879e33664241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[7]</value>
      <webElementGuid>82a8fb4d-bc04-4003-bae7-ed86c3bc7dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>251e5f4f-19fa-4c94-805b-39979370fb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6KG7eOZ0ooYj60lsPm2kIS79ohL8R0Qyo7Bw72UsQVliaKCE9hYdlSqFv8HeK-Bh3NLQvWYABrO1QBXuC94tHtYFsKZEofOEt6Hz46vTEwLacNYfpbRtSTg9FV6-pd4JQAFOKF8732pCoyRr92cix42xXHxs8l7oiqDqnoUDArTGRsktl3T_m6Ql1_22EpfoL9ECDVFJvx8Oqt0BBD58CrJClNgG4Lra1Gs4IYwFthtpXwH5M&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>afb3ff1a-4747-49f7-a42f-8b0a8220e347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
