<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_boats_rc-image-tile-33_1_2</name>
   <tag></tag>
   <elementGuidId>cb806b7d-f48d-41d9-ad99-180642869000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fec81b0d-6c7f-41a1-9a7a-6b77df01ab13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>bb8ec758-f4ab-42f1-9bf8-092ceac82ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>6977f8c6-4866-4a2e-a771-410269e258d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>bae3145e-c6b9-4416-bb72-e40348ee9abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>c71b6b9d-5a0a-4c01-9105-560042b3d403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>5f001aa4-be40-4bb0-a971-9359f7e12317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[7]</value>
      <webElementGuid>3b776683-b90a-4ac6-afa4-3b3e48060dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>d467e136-d8f4-4e1c-8edd-e2d39e6eaefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA52gSa1VdRfaS0nSFtS1cWX9H6iqYPVXAilRW_vCWJkCFTsiiSU-cDgaMO-lMOUQlRVHhd1kMfuoRTNU1efOcwRfIGpWlBEWM4m3TXzrnKFZcE3gz2A9TMknrpBXw9bQOqtzAwqHrc1_jg_z0sMR6wtiPwXb_2ENlGnFwzOdEVCV2Msq66JB90QRueTyCCZzx2ojMOeGDYR53TSnwsdI3nZWo9JGB0_YjwAL-UHpMRTkLgqKNw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>2abda642-e2e2-4b29-b013-fbf2f98d81e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
