<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2</name>
   <tag></tag>
   <elementGuidId>16918613-f38c-433b-b416-94502f86ab55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9b9dedf-b12a-4175-8a35-8f1ce2a4f58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>402173d1-af13-4643-90ca-d108e5c0db86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>f72650ab-231a-497c-92de-8657510ae7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>0df1a087-957a-48ec-a43b-1c580f732785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>27ca7c8b-2436-4864-87b0-5963041f99ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>2f6df1e8-1ee0-40dd-ad72-712aba1b8a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')]</value>
      <webElementGuid>d11580b0-a5d6-418d-a235-864c2654f509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>366b5acf-e1df-4537-ad80-d7b56cebda06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>3c234926-18de-42a9-8853-49b61bdf1818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
