<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1</name>
   <tag></tag>
   <elementGuidId>22dc6a4b-5837-4dd9-97d8-b255aab31dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a4c77e6-04c3-4d4a-b23a-4dac7917dad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>25577587-03be-423f-bf43-c7fca1ef95b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG</value>
      <webElementGuid>143db68e-6237-4009-9542-518c08f0f23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>050d8084-aa6f-4186-9fcf-93b0b397824a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Practo/Page_Practo Accounts/iframe_html1body1div3div2iframe1_c-h0ceivc4gms3</value>
      <webElementGuid>f65b3a10-96d3-447e-bcb1-e5dfdd0a2218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>a9aaffda-c585-4c8f-8b8b-93255c13742e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG')])[5]</value>
      <webElementGuid>a163cd15-c267-4c9d-9d66-6cbb9931e1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>bd15578d-22b8-4b52-8a4a-a2256260fa9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Ggxv_ylfE5Sx1AoVhjBYZoA1yFYPTyGJJN28x3lNcChgQ2HWnRu41fEKrcIxKxcIqgN7ygqZV0aPXJNVKWw0mB6BK_7AuVbObzM5N9GqWoaXFLUmCvCu4rv8Dp4S-W33qfDBvvIYSwZCnjLCuM9_QhvRPXEDc5KwBNXN1y_lDSo5DmDllxOH4sWrzG3FMr5awBQAl8e2WORnVSYWHuA-jp390fg6eEQbZxIfXaiXx9YJqxsw&amp;k=6LcgVBgUAAAAANU9A74W9CtzZ3NeJdhbGIoUbDXG']</value>
      <webElementGuid>06c8672c-2e29-4d51-8470-3d6a8d22d482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
