<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue</name>
   <tag></tag>
   <elementGuidId>78d72fda-90fa-4d51-a9ce-4569c106721b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles__TextContainer-sc-5941cr-0.cCBwan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/div/div[2]/form/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90a57958-7b5d-4d0f-a325-457b59c746ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__TextContainer-sc-5941cr-0 cCBwan</value>
      <webElementGuid>c70b60f7-ff0a-4621-8127-188f70278bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>035894f9-60d7-4694-b086-567fb7db428a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;styles__Container-sc-18s7njp-0 kHpfXk&quot;]/div[@class=&quot;styles__RightContainer-sc-18s7njp-6 fIjwRW&quot;]/div[@class=&quot;styles__WrapperContentRight-sc-18s7njp-2 dLLDFF&quot;]/div[@class=&quot;styles__Container-sc-1t0o980-0 fgFQqm&quot;]/form[1]/button[@class=&quot;styles__DefaultButton-sc-5941cr-1 dboIuH&quot;]/div[@class=&quot;styles__TextContainer-sc-5941cr-0 cCBwan&quot;]</value>
      <webElementGuid>fe2c6bc4-e4ea-4b8b-9297-39a8045aa0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div[2]/form/button/div</value>
      <webElementGuid>8776cb78-1fa3-40e8-b418-e34732ca17a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do not have an account?'])[1]/preceding::div[1]</value>
      <webElementGuid>0e966d22-fa12-49c2-8b85-b0b0b91c5d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register now'])[1]/preceding::div[2]</value>
      <webElementGuid>5ad9d179-27d0-46a5-9c65-c9307d755828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>cb215ed4-1f20-4ed6-94ba-117b5706bee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>8bf950c0-78c9-4c7c-99eb-6e4c33571d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>23133114-34e3-4f15-8cb9-3211dbc17e2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
