<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CLEAR</name>
   <tag></tag>
   <elementGuidId>c2a98cbb-2998-4982-ad04-dc26a2da3533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hw__searchInputClearBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-banner']/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CLEAR&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53903b48-cb3e-411e-8ae9-79f2ab7aec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>inputClearBtn</value>
      <webElementGuid>2dbb5af4-de14-4735-8670-c25dc24f7790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hw__searchInputClearBtn</value>
      <webElementGuid>7cf54a6f-be5d-4918-a2a9-804aaefcfaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLEAR</value>
      <webElementGuid>518a384c-1ca9-45c5-a64d-84433daffb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-banner&quot;)/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40&quot;]/div[@class=&quot;makeFlex primaryTraveler&quot;]/div[@class=&quot;hsw hswFullWidth hswNew widgetOpen&quot;]/div[@class=&quot;hsw_inner&quot;]/div[@class=&quot;hsw_inputBox selectHtlCity inactiveWidget activeWidget&quot;]/div[1]/div[1]/div[@class=&quot;autoSuggestPlugin  locus hsw_autocomplePopupNew&quot;]/div[@class=&quot;react-autosuggest__container react-autosuggest__container--open&quot;]/div[@class=&quot;hw__searchInputWrapper&quot;]/a[@class=&quot;hw__searchInputClearBtn&quot;]</value>
      <webElementGuid>fdfbd592-30df-4e9c-a1ab-f6e3ea92bcda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-banner']/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>613f96f6-a180-4990-b702-a0486229c7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CLEAR')]</value>
      <webElementGuid>47a4735f-1be6-40c1-8b24-3444e97da9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City, Property name or Location'])[1]/following::a[1]</value>
      <webElementGuid>ab2bbd39-a2db-49ac-8098-5ae93b093e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delhi'])[1]/preceding::a[1]</value>
      <webElementGuid>8569b781-d9b0-4ffd-b2a2-7807b6b188d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai'])[1]/preceding::a[1]</value>
      <webElementGuid>d908b11f-a61b-4559-b9b5-2ee44f66c7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLEAR']/parent::*</value>
      <webElementGuid>5ff91a92-b674-44e7-9a0d-2916f0d81379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a</value>
      <webElementGuid>014845c0-f655-401b-b65c-654d7edf0619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'CLEAR' or . = 'CLEAR')]</value>
      <webElementGuid>c131019b-a5a4-476f-a79a-c6872cfe28bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
