<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, Property name or Location_react_bd85b2_1</name>
   <tag></tag>
   <elementGuidId>a95cd14e-1f99-45aa-8831-a0895dad710f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.react-autosuggest__input.react-autosuggest__input--focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Pun']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Where do you want to stay?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>234c9f45-4446-472a-8788-2622a8a3444c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd8ed2a2-e3ed-41a0-b2d7-014782001fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>20f5b1f8-7c60-4ffb-9cff-f5a86a5120db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7e5512ca-14b7-48bb-8d4f-f03aca92d972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
      <webElementGuid>ad6e4710-d723-4e11-b1d7-b70368c28d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-autosuggest__input react-autosuggest__input--focused</value>
      <webElementGuid>385ca5d0-51ac-4ff6-b722-7fc7b080cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Where do you want to stay?</value>
      <webElementGuid>b1b05b0c-3fdd-49de-b4f7-1510bafbec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Where do you want to stay?</value>
      <webElementGuid>628c756d-d2f6-419d-9332-539d4953c420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pun</value>
      <webElementGuid>593e076a-adc8-472b-8d8e-dd23ca0d476c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-banner&quot;)/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40&quot;]/div[@class=&quot;makeFlex primaryTraveler&quot;]/div[@class=&quot;hsw hswFullWidth hswNew widgetOpen&quot;]/div[@class=&quot;hsw_inner&quot;]/div[@class=&quot;hsw_inputBox selectHtlCity inactiveWidget activeWidget&quot;]/div[1]/div[1]/div[@class=&quot;autoSuggestPlugin  locus hsw_autocomplePopupNew&quot;]/div[@class=&quot;react-autosuggest__container&quot;]/div[@class=&quot;hw__searchInputWrapper&quot;]/input[@class=&quot;react-autosuggest__input react-autosuggest__input--focused&quot;]</value>
      <webElementGuid>bbbc2e8d-0443-413b-a350-4f9f59513052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Pun']</value>
      <webElementGuid>0fe16063-0168-4838-b1a4-22c52baf0289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-banner']/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>624dcff6-2adb-44f3-916b-efb602cd4608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d4e72aef-e010-46a0-be90-d7a2603f7f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Where do you want to stay?' and @title = 'Where do you want to stay?']</value>
      <webElementGuid>41143a78-163b-4a44-8aed-b64d251c2e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
