<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, Property name or Location_react_4c0581</name>
   <tag></tag>
   <elementGuidId>0aec89de-1104-4688-ba3f-118efe00d627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.react-autosuggest__input.react-autosuggest__input--open.react-autosuggest__input--focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='P']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Where do you want to stay?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>624e7411-267e-4714-a8e1-176865291fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c3afa99-3ac3-4dc9-bd13-795650e6872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>402604f2-705b-4901-b45f-78878cdf2023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>e3727575-f899-424b-b89f-642a4da885c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
      <webElementGuid>6ce0b1c9-ec18-4c36-9de4-3974168d3916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-autosuggest__input react-autosuggest__input--open react-autosuggest__input--focused</value>
      <webElementGuid>d8041dd6-39ed-4ffe-a0e5-6410b9a1f677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Where do you want to stay?</value>
      <webElementGuid>b276bb1c-3c05-4e65-81cb-2ddb6c0f12d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Where do you want to stay?</value>
      <webElementGuid>5068a01b-033f-4b54-a650-3c48d1ae92a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>9c32113b-62cf-434b-94f5-3ab8de4c1e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-banner&quot;)/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40&quot;]/div[@class=&quot;makeFlex primaryTraveler&quot;]/div[@class=&quot;hsw hswFullWidth hswNew widgetOpen&quot;]/div[@class=&quot;hsw_inner&quot;]/div[@class=&quot;hsw_inputBox selectHtlCity inactiveWidget activeWidget&quot;]/div[1]/div[1]/div[@class=&quot;autoSuggestPlugin  locus hsw_autocomplePopupNew&quot;]/div[@class=&quot;react-autosuggest__container react-autosuggest__container--open&quot;]/div[@class=&quot;hw__searchInputWrapper&quot;]/input[@class=&quot;react-autosuggest__input react-autosuggest__input--open react-autosuggest__input--focused&quot;]</value>
      <webElementGuid>3c7b668d-d136-4080-bee5-61ed07522316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='P']</value>
      <webElementGuid>85e45d45-e959-4a20-ad6a-96c2b3a5361c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-banner']/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>db99a5a8-ebb3-4f43-9f15-23ffec96dd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2c62b9da-a0a8-4d12-a3a4-e76739a7ae93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Where do you want to stay?' and @title = 'Where do you want to stay?']</value>
      <webElementGuid>f79811b1-0b1d-4535-a0b1-34b10e9a1bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
