<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, Property name or Location_react_bd85b2_1_2</name>
   <tag></tag>
   <elementGuidId>da56447e-1f54-4779-9a8f-792f50f7a659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.react-autosuggest__input.react-autosuggest__input--focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Pune']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Where do you want to stay?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e663eff-01cf-4c40-9ae1-4dcf89203a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86b36ffe-829c-4b7b-9e33-e05510cfe16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>b43e4c33-063f-4bda-b625-712287ad8e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>275394d7-5389-46ce-80fa-54de4405bd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
      <webElementGuid>6358445b-b335-45ff-96a3-7cb746772410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-autosuggest__input react-autosuggest__input--focused</value>
      <webElementGuid>636ec74b-e47c-46ee-8fc5-0d3f03bb624e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Where do you want to stay?</value>
      <webElementGuid>984f5cd5-97d8-4aeb-8cb4-7fdc0422f159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Where do you want to stay?</value>
      <webElementGuid>d0bb4632-0f4b-4f6d-9c87-7d87ed42b4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pune</value>
      <webElementGuid>79da0dc0-f147-41ad-8022-d44cce7eb633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-banner&quot;)/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40&quot;]/div[@class=&quot;makeFlex primaryTraveler&quot;]/div[@class=&quot;hsw hswFullWidth hswNew widgetOpen&quot;]/div[@class=&quot;hsw_inner&quot;]/div[@class=&quot;hsw_inputBox selectHtlCity inactiveWidget activeWidget&quot;]/div[1]/div[1]/div[@class=&quot;autoSuggestPlugin  locus hsw_autocomplePopupNew&quot;]/div[@class=&quot;react-autosuggest__container&quot;]/div[@class=&quot;hw__searchInputWrapper&quot;]/input[@class=&quot;react-autosuggest__input react-autosuggest__input--focused&quot;]</value>
      <webElementGuid>0292d30a-e4c1-43c0-a1d0-8e3f2b5b7bbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Pune']</value>
      <webElementGuid>78049575-d846-46fd-8d1b-ddb628766e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-banner']/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>dd6533b1-3837-41e9-9a45-5af4c9f763d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ceaa7bd7-4195-4d8c-96b3-7c56474558f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Where do you want to stay?' and @title = 'Where do you want to stay?']</value>
      <webElementGuid>b6dc96ce-e7dc-4d19-b3d4-81bb14040f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
