<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ENG_commonModal__close</name>
   <tag></tag>
   <elementGuidId>dcd7561a-971a-4305-9fda-e28ae22ff2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.commonModal__close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;Personal AccountMyBiz Account Mobile Number ‎+91Continue Or Login/Signup With By&quot;i >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4c58fd0-9d82-484f-bc05-c043553f575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>closeModal</value>
      <webElementGuid>89afd5cd-2580-4e1e-8ecb-c29503aa3a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>commonModal__close</value>
      <webElementGuid>e6519b6b-b39c-4068-ad5a-eee8b73754b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;imageSliderModal modal displayBlock modalLogin dynHeight personal&quot;]/div[@class=&quot;imageSlideContainer&quot;]/section[@class=&quot;modalMain tcnFooter&quot;]/span[@class=&quot;commonModal__close&quot;]</value>
      <webElementGuid>28824ece-53c4-4536-a518-b00648658745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span</value>
      <webElementGuid>2e2114b3-7aa7-465d-bedb-daf5800d18a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/span</value>
      <webElementGuid>61233f6c-7216-4f83-b7db-e042e27229dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
