<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_PriceClear.Min5001500to5001500250050005000</name>
   <tag></tag>
   <elementGuidId>7172b80d-ce66-4354-aaec-0f807a716cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PriceClear......Min₹500₹1500to₹500₹1500₹2500₹5000₹5000+&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>b0cd6cd3-0246-4c72-973f-c73c8d831982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FR+9+z _2OLUF3</value>
      <webElementGuid>9dffd65f-9087-4d2e-a2f4-7b8d934d1fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PriceClear......Min₹500₹1500to₹500₹1500₹2500₹5000₹5000+</value>
      <webElementGuid>259d8f98-300e-44ec-a7bb-79ddd1c931c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;nt6sNV JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-2-12&quot;]/div[@class=&quot;DOjaWF gdgoEp col-12-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_0BvurA&quot;]/section[@class=&quot;FR+9+z _2OLUF3&quot;]</value>
      <webElementGuid>5570f47a-bcaf-4ce9-82ea-4df684364866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[2]</value>
      <webElementGuid>76a99ac4-8f06-4b0a-9dcf-9c8520384244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show 2 more'])[1]/following::section[1]</value>
      <webElementGuid>e72e0ccb-4fb8-4dc5-b63e-501262e39ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Theaters'])[1]/following::section[1]</value>
      <webElementGuid>66d3e5aa-c2d1-4609-9b26-9edb5171894d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]</value>
      <webElementGuid>7d6d73f9-1ad0-45fa-8d41-f5d68a17f2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'PriceClear......Min₹500₹1500to₹500₹1500₹2500₹5000₹5000+' or . = 'PriceClear......Min₹500₹1500to₹500₹1500₹2500₹5000₹5000+')]</value>
      <webElementGuid>1796922a-aa6c-4c70-8de9-8125eb4e792b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
