<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Stories(917)</name>
   <tag></tag>
   <elementGuidId>29fcb649-0a2b-4769-b1af-44e7eaf5e8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-tabs-1953760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-1953760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Stories(917)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>891920bb-a387-4db6-b458-7b28c9222b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>feedback-tab</value>
      <webElementGuid>d9243c40-c03e-4cc7-805b-3165039f95c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-tabs__tab</value>
      <webElementGuid>83aff8b8-25a0-42b3-97fd-288a96299f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>adaa7163-39b2-429a-8d48-db0780ce09aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-tabs-1953760</value>
      <webElementGuid>217908bf-510e-41b8-a08c-ba900f37c95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a5da85c-556d-4092-bec9-8b5ecf0fc25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53289759-f0ae-4f5b-aef5-262d440e8a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-tabs-1953761</value>
      <webElementGuid>922b4710-e78c-4031-8242-fbaeaaced524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stories(917)</value>
      <webElementGuid>22635865-ad58-4c11-921b-84d82d18b2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-1953760&quot;)</value>
      <webElementGuid>f86e4ed5-743d-4ac8-b991-49ac7d55d7d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-1953760']</value>
      <webElementGuid>6cb59646-d1b9-4682-ba53-d6f786dc10e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div/div[2]/ul/li[2]</value>
      <webElementGuid>b0effc87-f922-4c77-8cc0-17cfd1e4defa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::li[1]</value>
      <webElementGuid>f914f377-8e23-41b9-835d-80cb7f9afc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share your story'])[1]/following::li[2]</value>
      <webElementGuid>49565f6c-1c5e-4db8-a927-238c6a5d911d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>4ece4e6c-e8dc-4e8f-8ba7-a1f0ab3ba443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'react-tabs-1953760' and (text() = 'Stories(917)' or . = 'Stories(917)')]</value>
      <webElementGuid>c23865ec-b075-4b97-bfb6-3afb999a3582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
