<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Healthfeed</name>
   <tag></tag>
   <elementGuidId>e4e35f1b-8aa6-4c0f-8810-978dd47ab0ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-tabs-1953764 > button.c-btn--unstyled > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-1953764']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Healthfeed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6125512-506d-4aa0-974d-0e2e602c3826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Healthfeed</value>
      <webElementGuid>eb7e7375-bcb4-43c8-8ca5-bc7b6ad3a8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-1953764&quot;)/button[@class=&quot;c-btn--unstyled&quot;]/span[1]</value>
      <webElementGuid>52e50bad-0a2d-47d2-a5ec-618fc4038fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-1953764']/button/span</value>
      <webElementGuid>26d79c95-e744-4c2c-b14b-d7ca9bf3de07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consult Q&amp;A'])[1]/following::span[1]</value>
      <webElementGuid>1039849d-6b71-40dc-b888-1d955b250aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stories'])[1]/following::span[2]</value>
      <webElementGuid>96f9c699-94cf-4e0b-84ac-3028b81fdc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Stories for'])[1]/preceding::span[1]</value>
      <webElementGuid>c61a0ad0-c3f0-48fb-aec0-b41eee16400b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. Sandeep Bhirud'])[3]/preceding::span[2]</value>
      <webElementGuid>da6d90e6-530b-4cb8-98d8-9d980ec8e9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Healthfeed']/parent::*</value>
      <webElementGuid>4482f09d-58b4-41cc-867b-6aefe7a3d11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/span</value>
      <webElementGuid>fbc936eb-8b28-4512-aa8e-11e57682f6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Healthfeed' or . = 'Healthfeed')]</value>
      <webElementGuid>5f8918f4-1630-4ee0-a9db-eedbb31597fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
