<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chennai</name>
   <tag></tag>
   <elementGuidId>9f5822aa-1aee-4a5b-8779-1d787d4624c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ExploreZolostyledesktop__City-sc-1d5lty1-4.ftHbXg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[4]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Chennai&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6e9af1d-0548-44da-84f5-8af75c670880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ExploreZolostyledesktop__City-sc-1d5lty1-4 ftHbXg</value>
      <webElementGuid>784db320-3a68-4206-bb49-74400a3b85b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chennai</value>
      <webElementGuid>790a9f50-23eb-45e1-893d-bae5dec838a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ListingViewmobile__ListingViewWrapper-sc-1tqy948-8 eTSVv&quot;]/div[@class=&quot;ExploreZolostyledesktop__Container-sc-1d5lty1-0 kLIyTT&quot;]/div[@class=&quot;ExploreZolostyledesktop__TopBar-sc-1d5lty1-1 gzaAzZ&quot;]/div[@class=&quot;ExploreZolostyledesktop__CityList-sc-1d5lty1-3 fWnKJY&quot;]/div[@class=&quot;ExploreZolostyledesktop__City-sc-1d5lty1-4 ftHbXg&quot;]</value>
      <webElementGuid>3fdf1649-ce57-47b1-8b41-ac7818d77f09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/div[2]</value>
      <webElementGuid>78c157b3-9df2-452c-b3e2-426782bc7adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bangalore'])[1]/following::div[1]</value>
      <webElementGuid>53fb0fe3-3764-4d61-819c-9aee2f41568a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more'])[1]/following::div[5]</value>
      <webElementGuid>c64b837c-ae56-4b95-9441-13ce390f1994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coimbatore'])[1]/preceding::div[1]</value>
      <webElementGuid>300ddf60-58ac-448e-9566-9f68067dc1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delhi'])[1]/preceding::div[2]</value>
      <webElementGuid>beb1e9bf-1ca1-43de-a986-d4084052b279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chennai']/parent::*</value>
      <webElementGuid>9bb279ce-502d-4f1d-92e0-a151bc4044d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]</value>
      <webElementGuid>dc435c08-2964-4520-9c78-67708f0bf604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Chennai' or . = 'Chennai')]</value>
      <webElementGuid>0e4e7c28-4709-42d9-9779-5a2b0f245c25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
