<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Ocean View</name>
   <tag></tag>
   <elementGuidId>d640fb3b-09a8-4f2b-9761-5f40b804f115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/section/div/div/div[12]/div/ul/li[6]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ocean View&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e047db07-045c-4e64-b9c7-87a182f172ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FilterPillsListstyles__FilterText-sc-1thx3gf-6 vVtQG</value>
      <webElementGuid>cad114e0-f9da-4b6c-97e8-4cc43ae5fea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ocean View</value>
      <webElementGuid>5e934ed3-81c3-40bf-b0d6-41d4d4019d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;AppOnlineOffline__ContainerOfflineSpan-sc-1p9o9u6-0 cEnHqJ&quot;]/div[@class=&quot;dwebCommonstyles__BaseColumnWrap-sc-112ty3f-2 civGJZ&quot;]/div[@class=&quot;SRPstyles__BodyWrapperContentStyle-sc-1uttzk9-1 hhbmZR&quot;]/section[@class=&quot;SRPstyles__LeftSectionWrapperStyle-sc-1uttzk9-3 iBIsNh&quot;]/div[1]/div[@class=&quot;FilterScreenstyles__FilterModalScreenContentWrapper-sc-1kumrxq-0 MDeWN&quot;]/div[@class=&quot;FilterScreenstyles__FilterComponentWrapper-sc-1kumrxq-1 eATbkT&quot;]/div[@class=&quot;FilterScreenstyles__FilterContentOuterWrapper-sc-1kumrxq-6 fuMRZJ&quot;]/ul[@class=&quot;FilterScreenstyles__FilterContentWrapper-sc-1kumrxq-7 ddpqeK&quot;]/li[@class=&quot;FilterPillsListstyles__FilterPillItem-sc-1thx3gf-4 eGNQjO&quot;]/div[@class=&quot;FilterPillsListstyles__ContainerWithCheckbox-sc-1thx3gf-12 hwJQbs&quot;]/p[@class=&quot;FilterPillsListstyles__FilterText-sc-1thx3gf-6 vVtQG&quot;]</value>
      <webElementGuid>0f335367-64a2-4a7a-9fe1-4fb989131882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/section/div/div/div[12]/div/ul/li[6]/div/p</value>
      <webElementGuid>ee345abf-2aea-4bf4-96db-86052db858d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ocean View']/parent::*</value>
      <webElementGuid>88992dc1-76d3-4a4f-8cab-ab6c8e879d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/ul/li[6]/div/p</value>
      <webElementGuid>d5c73af3-1472-416d-b59b-5212e2377bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Ocean View' or . = 'Ocean View')]</value>
      <webElementGuid>9cb4c4bb-a4a4-4a12-ba8d-783f6abb3662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
