<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>7a16aa90-d328-455e-bfb1-9b4bd74eaece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Textstylecommon__Txt-sc-4w6sg8-0.bBoEFh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Search..&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47fe10d6-3be1-442c-b2a3-b7886c6744f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>textComponent</value>
      <webElementGuid>fb8ee7f2-af45-4f9a-b2fa-8680ef774550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#808080</value>
      <webElementGuid>0984a2f7-3818-448e-ac7f-40c88b23ab39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>b23be9dc-6be2-47d4-bfa3-fdf91442b54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>6041ab11-83a1-4198-aeea-f1eef82f858e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-style</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>396a8aad-b330-4dad-b08c-6de3ba730705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a85666c0-5610-49e4-9f37-1833c8a9bc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>cead431d-4df1-4546-82b2-adb2ac548c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f21d5bc4-e777-41da-94e6-f986e18fcebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstylecommon__Txt-sc-4w6sg8-0 bBoEFh</value>
      <webElementGuid>845a7e83-b099-4f66-a2dd-b1c02917e922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overflow</name>
      <type>Main</type>
      <value>initial</value>
      <webElementGuid>4f97276d-b542-4e4d-a4f5-ecbad9587177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>display</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>1d9c19b2-0a10-424c-8f83-f931cc4ba198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search..</value>
      <webElementGuid>0179aab8-3476-4ea5-87d2-6f6f67b89dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Headerstyledesktop__Container-sc-yl1aqv-0 eoApsK&quot;]/div[@class=&quot;Headerstyledesktop__SearchArea-sc-yl1aqv-1 gGayzv&quot;]/div[@class=&quot;Headerstyledesktop__SearchPlaceholder-sc-yl1aqv-3 fHgbvS&quot;]/div[@class=&quot;Textstylecommon__Txt-sc-4w6sg8-0 bBoEFh&quot;]</value>
      <webElementGuid>aa5a929c-ca86-42ed-91dd-2b3a926542c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div</value>
      <webElementGuid>4d6abe9d-d4ec-4786-926f-e86363028186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Header_Cities'])[1]/following::div[3]</value>
      <webElementGuid>441d8b50-b71e-4beb-bdad-44a3b2b8a708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::div[7]</value>
      <webElementGuid>68bcb25a-d1ff-42a7-bdf2-1460da6eb61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN IN'])[1]/preceding::div[1]</value>
      <webElementGuid>36953f33-4c32-4365-b330-747c952bbe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search..']/parent::*</value>
      <webElementGuid>19f49e9d-0e2a-4746-b685-709bda948e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>3aeb16b5-d0ee-47a9-b43d-8a2b2e6b694e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Search..' or . = 'Search..')]</value>
      <webElementGuid>f282ec93-2f6f-4f79-8dc9-f216b23841be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
