<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Coimbatore</name>
   <tag></tag>
   <elementGuidId>300adaa8-8223-4a01-b4b8-5fce6971b424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CityCard_stylesdesktop__Container-sc-kme8v3-0.gXFclL > div.Textstylecommon__Txt-sc-4w6sg8-0.ibvYrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Slot_item_2']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Slot_item_2 [data-testid=&quot;textComponent&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61f7a7cf-86ce-480f-8a12-984d40be5557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>textComponent</value>
      <webElementGuid>07825478-043b-426c-ae2d-e8ff081a0ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#B8B7B7</value>
      <webElementGuid>e31784f1-72cc-4d1b-8be2-0755495bc4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>beaf18e2-bc2d-45e9-90bb-fe1f0428d24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2e8926cb-0f0f-4a2f-9c85-48abc6e78ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-style</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>389e1e7e-64da-419b-9a00-0c677d6b8f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>80a5b640-83eb-46b9-92e8-61386e8103a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>d45e48ad-8f48-42d3-85ea-0d6a43183a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>521a1c41-54fc-44cc-ae68-710bc4396280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl</value>
      <webElementGuid>1675c2ac-5974-4fc8-b593-5db818810202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overflow</name>
      <type>Main</type>
      <value>initial</value>
      <webElementGuid>5766d7a1-b697-4aaf-9e62-c3000e1c6dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>display</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>2aba7c6f-8b71-4f5f-9c3c-3c73f58a524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coimbatore</value>
      <webElementGuid>267b12fb-d34a-4d23-9278-ca687f638c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Slot_item_2&quot;)/div[1]/div[@class=&quot;CityCard_stylesdesktop__Container-sc-kme8v3-0 gXFclL&quot;]/div[@class=&quot;Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl&quot;]</value>
      <webElementGuid>d73980d0-a0db-4ba0-8f56-81cd5e9d9197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Slot_item_2']/div/div/div</value>
      <webElementGuid>405e4a7d-2ac3-4936-be71-c218a2516106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[2]/following::div[4]</value>
      <webElementGuid>57ba4498-04d8-4a8b-9c87-f0f0c9070796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bangalore'])[2]/following::div[8]</value>
      <webElementGuid>876d8dba-bfd5-40fb-979d-9095c8a5724a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pune'])[2]/preceding::div[2]</value>
      <webElementGuid>bdfb8a11-9ac3-499c-bb1b-67111c97d474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hyderabad'])[2]/preceding::div[6]</value>
      <webElementGuid>388f09e1-7377-4c02-b96c-cd8804be6c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div</value>
      <webElementGuid>732fbf75-f98d-4335-ba48-a76968f8d16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Coimbatore' or . = 'Coimbatore')]</value>
      <webElementGuid>25de9b71-b812-49a4-8c35-18904e21cb00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
