<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AC</name>
   <tag></tag>
   <elementGuidId>9991ad6f-81c0-4a23-9e79-97307e48de73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Chipstyle__Container-sc-tvaied-0.kNSDcG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[8]/div/div/div/div[2]/div/div[4]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AC&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>676bc0de-9016-4a2f-9e47-8608eccbfbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4913de53-98d0-4cc5-9fcb-ef74d2bd649f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>b7c35b18-7ae5-4cf5-9402-0c290ab3a2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>0a6c533c-b1e5-472a-8934-6899606e586f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>777b75fa-c752-4ca8-811b-0f2f74f57377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#757575</value>
      <webElementGuid>36dbb15a-a0b5-4ee1-b3a9-b91e969336f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Chipstyle__Container-sc-tvaied-0 kNSDcG</value>
      <webElementGuid>60f9e4a6-6e59-4e92-bdd1-0a4d176155a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AC</value>
      <webElementGuid>244ba3bf-66da-4e50-869b-88534f3f6ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;SearchViewdesktop__Container-sc-agibtv-1 jvkOnc&quot;]/div[@class=&quot;AnimateItemstylecommon__SlideInAnimation-sc-g0wgo6-1 hrlPgV&quot;]/div[@class=&quot;SearchViewdesktop__Tab-sc-agibtv-2 jzGhXH in&quot;]/div[@class=&quot;SearchFiltersstyledesktop__Container-sc-rwkhep-0 dLdCKm&quot;]/div[@class=&quot;SearchFiltersstyledesktop__SearchBodyWrapper-sc-rwkhep-16 djoVSA&quot;]/div[@class=&quot;SearchFiltersstyledesktop__FilterCards-sc-rwkhep-8 jVhlxo&quot;]/div[@class=&quot;SearchFiltersstyledesktop__FilterCardWrapperWithMenu-sc-rwkhep-9 hnQtZP&quot;]/div[@class=&quot;FilterCardstyle__ChipContainer-sc-l27nhm-0 ikGWFC&quot;]/div[@class=&quot;Chipstyle__Container-sc-tvaied-0 kNSDcG&quot;]</value>
      <webElementGuid>86391436-6e39-4304-b6ef-2467394eb675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[8]/div/div/div/div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>06a3c899-ca5d-49ac-a1bd-a06ad5c3dd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amenities'])[2]/following::div[2]</value>
      <webElementGuid>a7973204-f364-485f-9648-cc3651111aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joining Date'])[1]/following::div[5]</value>
      <webElementGuid>ec943167-6d14-4af5-a0bb-a240fb3a15a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Food'])[1]/preceding::div[1]</value>
      <webElementGuid>8e93ab48-562a-4421-85e3-0acd96251587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fridge'])[1]/preceding::div[2]</value>
      <webElementGuid>2211ca95-249a-4e13-84fc-4e6e47b87eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AC']/parent::*</value>
      <webElementGuid>1130ff50-ac1c-4db4-b449-7c58bdbbf6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>e0064946-b1b1-43f2-9010-c5906a36cd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AC' or . = 'AC')]</value>
      <webElementGuid>0e68ec53-0b67-48c5-aae6-73a10a7509b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
