<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b08167d2-6cc5-4f11-8b5a-b0fc1010ca07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;toggle-menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-img-header-mobile']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;toggle-menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>37543af0-eaab-4c6f-8845-f263b6834d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>toggle-menu</value>
      <webElementGuid>e0cfdf0a-6b2f-4fbf-9df5-301508bf5664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1dykungmee0hk.cloudfront.net/themes/skillate/images/menubutton.svg</value>
      <webElementGuid>e9aee553-1d76-4c55-98a0-1d6f5d69e2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-img-header-mobile&quot;)/img[1]</value>
      <webElementGuid>228e5435-cc9b-4e8a-b115-085da9f8c2e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-img-header-mobile']/img</value>
      <webElementGuid>085fd1fb-5ec0-409a-95bc-1898d008f4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='toggle-menu']</value>
      <webElementGuid>a1fc1b33-d008-48ea-88bc-103c2ebb43d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>e682521e-b8cd-4c91-b354-91ba8c30f80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'toggle-menu' and @src = 'https://d1dykungmee0hk.cloudfront.net/themes/skillate/images/menubutton.svg']</value>
      <webElementGuid>57fa1950-a005-4496-978e-123789cde0ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
