<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>85f987f5-1fec-40d8-ba02-fb39a32ca046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Mumbai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f37573d-7b3a-487e-bbc1-5fbb360e7511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d594140-ab79-41ad-ba96-8edf58763e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Mumbai</value>
      <webElementGuid>503bfcc4-bf11-4e55-bef6-e1762d863d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 bPZJjI&quot;]/div[@class=&quot;sc-1gt8xf5-3 helaNf&quot;]/div[@class=&quot;sc-12foipm-16 wfIEw&quot;]/div[@class=&quot;sc-12foipm-0 iiZOql&quot;]/div[@class=&quot;sc-12foipm-20 jPzQOy&quot;]/div[@class=&quot;sc-12foipm-22 OmQvV&quot;]/div[@class=&quot;sc-12foipm-24 bDSkOK&quot;]/div[@class=&quot;sc-12foipm-25 fbAAhv&quot;]/input[1]</value>
      <webElementGuid>9fdd214c-8844-4f0b-ba40-728e8b68baf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Mumbai']</value>
      <webElementGuid>89ca6622-5817-4376-8bca-c3562dd8cee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>8b85f2de-389a-4310-b2c9-c3c7057db97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>48471fb7-f1f3-4360-ae06-5bd3c3582811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c051882a-1bef-4fb0-a9d1-e8ba2daa9c00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
