<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text</name>
   <tag></tag>
   <elementGuidId>5e935c81-f21c-4ec6-a01c-76d03580ec2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='P']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72dadb47-cbcb-40a2-9999-340b2068c811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30a0287b-41e7-4d65-b3f2-3587ae716f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>8e96701f-a454-4b41-a577-c3e9f03bbf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 bPZJjI&quot;]/div[@class=&quot;sc-1gt8xf5-3 helaNf&quot;]/div[@class=&quot;sc-12foipm-16 wfIEw&quot;]/div[@class=&quot;sc-12foipm-0 iiZOql&quot;]/div[@class=&quot;sc-12foipm-20 jPzQOy&quot;]/div[@class=&quot;sc-12foipm-22 kGtxGm&quot;]/div[@class=&quot;sc-12foipm-24 bDSkOK&quot;]/div[@class=&quot;sc-12foipm-25 fbAAhv&quot;]/input[1]</value>
      <webElementGuid>a685b1e1-12a3-4bb2-a285-dc4334b15385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='P']</value>
      <webElementGuid>5c307ddb-f0b1-41f4-8174-e5f473d8d27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>44f0850c-a0c5-49a4-9f95-3aa21ce4d1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>169c7e37-3eb2-4759-a5d6-3800eaa4dfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>137e3dd3-2333-4968-bbc8-42f40e32e35c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
