<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(BOM)</name>
   <tag></tag>
   <elementGuidId>3d0038ea-2dbc-4b56-9ae4-bdbbd53842af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.autoCompleteSubTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='autoSuggest-list']/li/div/div/div/p/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;(BOM)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f871296e-05f1-4961-885a-f21f0fb42026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoCompleteSubTitle</value>
      <webElementGuid>0c7b38fa-1687-46da-a2af-730cbb825393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(BOM)</value>
      <webElementGuid>db62ad42-e506-42f5-aede-eed9410ee61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoSuggest-list&quot;)/li[@class=&quot;sc-12foipm-28 caQpDt active&quot;]/div[@class=&quot;sc-12foipm-29 gEpyDY&quot;]/div[@class=&quot;sc-12foipm-30 izHctt&quot;]/div[@class=&quot;sc-12foipm-32 jVTqNw&quot;]/p[@class=&quot;sc-12foipm-33 kUcHKT&quot;]/span[@class=&quot;autoCompleteSubTitle&quot;]</value>
      <webElementGuid>470cd0cf-4f98-48d5-8b42-73b9edb37092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='autoSuggest-list']/li/div/div/div/p/span[2]</value>
      <webElementGuid>ae742b48-c773-4ad6-8c4e-69abd5fe0776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[2]/following::span[3]</value>
      <webElementGuid>b05ae19e-d557-4c51-9b04-56a6cc6e7a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IN'])[1]/preceding::span[1]</value>
      <webElementGuid>30dbef61-306e-4433-9be4-95674b86a7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(']/parent::*</value>
      <webElementGuid>7d7b8fdf-60a0-45ff-9797-e87e8cd4a4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span[2]</value>
      <webElementGuid>1290b82a-89fa-4401-8122-f6889bca17fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '(BOM)' or . = '(BOM)')]</value>
      <webElementGuid>43bc221d-79fe-4b52-aeea-f0b8846d9dec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
