<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daily Steal Deals  Special Discounts_l_c0692f</name>
   <tag></tag>
   <elementGuidId>d3e8d4d6-802e-416c-a091-66db524a147e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.logSprite.icClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.logSprite</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1691647d-2363-40ce-8c0e-f6bd7ee21d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logSprite icClose</value>
      <webElementGuid>6c6f3ca6-484f-428c-bc5a-5b7a4252bf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>32068531-73ba-4eec-8739-9c989dcb97a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop&quot;]/div[@class=&quot;sc-hwdzOV hAlsJg modal-wrapper&quot;]/div[@class=&quot;sc-jaXxmE hxDJGS&quot;]/div[@class=&quot;sc-jGKxIK dUoHid&quot;]/div[@class=&quot;sc-jsJBEP guMGBh&quot;]/div[@class=&quot;sc-eeDRCY QfmYf&quot;]/span[@class=&quot;sc-koXPp bDtzaf&quot;]/span[@class=&quot;logSprite icClose&quot;]</value>
      <webElementGuid>c374c788-1ea7-4aa4-9c45-d6d762ff2ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>f177eefd-3789-4560-961c-f68029f7c2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
