<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FROM_autosuggestBusSRPSrcHomeName</name>
   <tag></tag>
   <elementGuidId>34157b83-9d5f-407d-8b72-9d5c6e785282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autosuggestBusSRPSrcHome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autosuggestBusSRPSrcHome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Source&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70681d7e-b915-4924-8c83-1c9948f2824b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c7092fc-cda7-421d-b4c5-54e605a2a85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3036141f-2e14-42cc-b6f1-f3765255da9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autosuggestBusSRPSrcHomeName</value>
      <webElementGuid>35896ce8-59f6-4907-95bb-9075fc5fdcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>10a27545-7c29-4e68-8d56-8e61af1b0e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-1-label</value>
      <webElementGuid>7bcce2ee-017c-4f99-a742-596a4c02daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>875cb82f-5473-49f3-a832-145587161946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autosuggestBusSRPSrcHome</value>
      <webElementGuid>484da571-5ee8-43d2-a03c-23675f316255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Source</value>
      <webElementGuid>7e196355-8c25-43b5-b29a-9d4d30ed0f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autosuggestBusSRPSrcHome&quot;)</value>
      <webElementGuid>2d22f958-df39-40d1-a832-5287a9870373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autosuggestBusSRPSrcHome']</value>
      <webElementGuid>2a8d52c0-7251-4f61-877a-a5a962b35416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/section/section/div/div/input</value>
      <webElementGuid>bccb6f2d-70b0-4374-92a2-2b32b9216440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c02ee8e8-a523-4882-8d5e-fea7a7c9a5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'autosuggestBusSRPSrcHomeName' and @id = 'autosuggestBusSRPSrcHome' and @placeholder = 'Enter Source']</value>
      <webElementGuid>87b21141-608f-40c6-9e0a-174a3fe0fffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
