<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TO_autosuggest</name>
   <tag></tag>
   <elementGuidId>e8065cd9-fc60-411a-9ef9-3eb7d2978f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autosuggestBusSRPDestHome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autosuggestBusSRPDestHome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Destination&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f47646a-3841-45ac-8d8c-776f465d7c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76649592-27d7-4581-88ef-2c187f8f6a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autosuggest</value>
      <webElementGuid>84e7af45-48d7-4274-a3cb-c04ef7b94da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>80dff738-1e07-4448-bd10-a58827d10aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>5f86d11b-3c88-47a6-a988-f0a2e171c541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-2-label</value>
      <webElementGuid>cee4f098-4186-4d8a-b8da-6d8ef5d4eef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a96e193-023f-4325-b22d-29013e46ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autosuggestBusSRPDestHome</value>
      <webElementGuid>8df9879d-3323-4f2b-8f53-90de72a265a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Destination</value>
      <webElementGuid>cc2feed3-cd10-4898-8e95-39f52d828f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autosuggestBusSRPDestHome&quot;)</value>
      <webElementGuid>97c41fb6-7da7-4ec9-a6ba-5bac926c2501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autosuggestBusSRPDestHome']</value>
      <webElementGuid>f7c8ae85-a465-4e80-ac4c-a21e1ae1abe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/section/section/div[2]/div/input</value>
      <webElementGuid>714e332a-4833-4cfe-abe9-6dcf06eaa936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>46659d4b-a69c-4b18-b9e4-c3d037c37ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'autosuggest' and @id = 'autosuggestBusSRPDestHome' and @placeholder = 'Enter Destination']</value>
      <webElementGuid>98d3d77a-28e2-4bf5-af7c-de81bd717af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
