<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Healthfeed</name>
   <tag></tag>
   <elementGuidId>be5a05cc-e858-4df0-aa30-bea159fec568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-tabs-740772 > button.c-btn--unstyled > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-740772']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Healthfeed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2fbb30ef-800f-4075-837e-e43129ca61fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Healthfeed</value>
      <webElementGuid>07eed076-e7fc-4455-9b7f-66b761b7c602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-740772&quot;)/button[@class=&quot;c-btn--unstyled&quot;]/span[1]</value>
      <webElementGuid>b38ce1ac-896f-453c-8c92-1a811ba22a0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-740772']/button/span</value>
      <webElementGuid>bd0e94b3-6583-42bc-8223-76d7398b7c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consult Q&amp;A'])[1]/following::span[1]</value>
      <webElementGuid>9cfdf09c-fdfb-4a9e-a12a-3b2aaa2bec23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stories'])[1]/following::span[2]</value>
      <webElementGuid>7a303cd7-666f-4c79-b29c-4b5c67546225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potty problem'])[1]/preceding::span[2]</value>
      <webElementGuid>e942f68e-2918-4811-adfd-3acbf49f8b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Healthfeed']/parent::*</value>
      <webElementGuid>816b28d1-0416-402c-9347-57b461d2afdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/span</value>
      <webElementGuid>82da9396-3d30-489f-965e-78c965df6420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Healthfeed' or . = 'Healthfeed')]</value>
      <webElementGuid>fd4fbb55-dc36-4580-b8b4-0e30fc162122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
