<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Stories</name>
   <tag></tag>
   <elementGuidId>768e0e2a-6445-4b2d-9410-b4ced52974d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-tabs-740768 > button.c-btn--unstyled > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-740768']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Stories(204)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fdabf48e-38a1-4600-ba26-2b1b0331a89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stories</value>
      <webElementGuid>7780c2f1-1154-4b19-8d09-ac14fac20338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-740768&quot;)/button[@class=&quot;c-btn--unstyled&quot;]/span[1]</value>
      <webElementGuid>b930c610-0724-458b-8117-80a569f47258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-740768']/button/span</value>
      <webElementGuid>6e098123-dbb5-4b11-adf5-6b27ce0ea157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::span[1]</value>
      <webElementGuid>f932c096-0a45-4e67-a808-f17a3861102f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consult Q&amp;A'])[1]/preceding::span[1]</value>
      <webElementGuid>338af588-77b4-49e2-a5ae-eae4b1858860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Healthfeed'])[1]/preceding::span[2]</value>
      <webElementGuid>0d1b390b-d607-4620-b0c5-ba6732b52e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stories']/parent::*</value>
      <webElementGuid>04b2cf29-e1b2-4eff-aedd-c556784d69ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/span</value>
      <webElementGuid>71d2bda0-6cec-4f32-aca2-20182bd98a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Stories' or . = 'Stories')]</value>
      <webElementGuid>3e169372-662e-4d88-9c23-39d980ceacc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
