<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Stories(333)</name>
   <tag></tag>
   <elementGuidId>4862f477-5725-425b-a684-4dea080828e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-tabs-2248148 > button.c-btn--unstyled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-2248148']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Stories(333)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1edc587-3637-45ec-855b-9855f35ebf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-btn--unstyled</value>
      <webElementGuid>fbfb5660-9f76-4e18-9103-c228f0ca5769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>972e85b3-c5d3-42cd-a73b-c28c91495313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stories(333)</value>
      <webElementGuid>7e8ba419-18ee-4d7d-95f5-99f32efd7264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-2248148&quot;)/button[@class=&quot;c-btn--unstyled&quot;]</value>
      <webElementGuid>e7df3381-8ee3-4ee8-a28c-563b4711e033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-2248148']/button</value>
      <webElementGuid>a0595b59-8dd6-4579-89a1-1c498f37121f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::button[1]</value>
      <webElementGuid>b75835dd-7548-47bc-871c-1be5380ef65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share your story'])[1]/following::button[2]</value>
      <webElementGuid>250c69df-2a4b-4499-96f0-5ef5039150ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consult Q&amp;A'])[1]/preceding::button[1]</value>
      <webElementGuid>bbc0674c-8532-4eb8-a5f6-f4dcb6f514ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(333)']/parent::*</value>
      <webElementGuid>ccf3cbdf-d005-49c3-8102-3d5dc0747328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>a8040c81-db85-4675-83f0-38403d4c275c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Stories(333)' or . = 'Stories(333)')]</value>
      <webElementGuid>181e2091-0f0c-4ec6-a015-d555c1108a56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
