<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gurugram</name>
   <tag></tag>
   <elementGuidId>1083d5f6-d04f-4f16-821f-1120965ae945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CityCard_stylesdesktop__Container-sc-kme8v3-0.evhHiA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[9]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Gurugram is a picturesque Gurugram&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>222658bb-89fb-4e4c-b8f8-32b13b781ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CityCard_stylesdesktop__Container-sc-kme8v3-0 evhHiA</value>
      <webElementGuid>cf68a5b7-df9f-4bb9-8796-d8208dc35567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gurugram</value>
      <webElementGuid>af101e0b-006f-486b-bf1c-ea2c0b369153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;HomeViewdesktop__Container-sc-1llz785-29 fjeEdZ&quot;]/div[@class=&quot;HomeViewdesktop__HeroSectionWrapper-sc-1llz785-30 fkVtLO&quot;]/div[@class=&quot;HomeViewdesktop__CityCardWrapper-sc-1llz785-33 kHygRA&quot;]/a[9]/div[@class=&quot;CityCard_stylesdesktop__Container-sc-kme8v3-0 evhHiA&quot;]</value>
      <webElementGuid>e74f82b6-0c9e-4bdd-b133-012d35df40f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[9]/div</value>
      <webElementGuid>357de4b5-de9d-4d73-ab06-3d39dcd5969d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai'])[1]/following::div[1]</value>
      <webElementGuid>819618db-d6c7-4a2f-85c5-1abb7577b225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delhi'])[1]/following::div[3]</value>
      <webElementGuid>2954931e-7b06-40d7-9541-a7cc6703b807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIND'])[1]/preceding::div[2]</value>
      <webElementGuid>2db260c2-c3ac-49ce-935f-21af3623aa4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]/div</value>
      <webElementGuid>7195911b-c67c-43df-855c-2175c5aa320f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gurugram' or . = 'Gurugram')]</value>
      <webElementGuid>9235dfa7-5893-4955-ab30-9d85fec9e5b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
