<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mumbai</name>
   <tag></tag>
   <elementGuidId>c3e68c63-8915-4f25-a53c-b753358e7f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CityCard_stylesdesktop__Container-sc-kme8v3-0.BJorW > div.Textstylecommon__Txt-sc-4w6sg8-0.ibvYrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[8]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mumbai is a picturesque Mumbai&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa999df7-2432-4b2f-8b07-45ab2e8ffe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>textComponent</value>
      <webElementGuid>ee855900-7cfe-4fd3-a5f0-b493313255ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#B8B7B7</value>
      <webElementGuid>478345a6-2864-4b89-887f-1fb4bfde4139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>96647667-cc3e-4add-87a6-6823fcf7687a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>dccca98c-15f6-4c2a-a734-8e45b59dc574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-style</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>bb968141-ef38-4f55-bfe3-60f9bbfe62fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>122cd5c4-cb79-4da6-a2c5-15377bdde540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>04c369dc-4117-479e-8127-436ab1cc6b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>854532b4-7598-446e-bafc-0bd2a335ba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl</value>
      <webElementGuid>2d38170c-c637-4df2-827a-d10c840b4a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overflow</name>
      <type>Main</type>
      <value>initial</value>
      <webElementGuid>9cb94976-919b-4f9a-9953-db26ec4dde4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>display</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>933a3d14-d5e8-49f0-b8cc-50e3965bc29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mumbai</value>
      <webElementGuid>5769657c-a6f9-42d2-a761-b8ea8924aff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;HomeViewdesktop__Container-sc-1llz785-29 fjeEdZ&quot;]/div[@class=&quot;HomeViewdesktop__HeroSectionWrapper-sc-1llz785-30 fkVtLO&quot;]/div[@class=&quot;HomeViewdesktop__CityCardWrapper-sc-1llz785-33 kHygRA&quot;]/a[8]/div[@class=&quot;CityCard_stylesdesktop__Container-sc-kme8v3-0 BJorW&quot;]/div[@class=&quot;Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl&quot;]</value>
      <webElementGuid>475b5cbe-4d53-4f86-b577-c53b3a6d2c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[8]/div/div</value>
      <webElementGuid>0c361968-a31d-4005-9e22-1eee04b164a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delhi'])[1]/following::div[2]</value>
      <webElementGuid>0e0830d6-aec6-4a3b-8269-eed2bd3548c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noida'])[1]/following::div[4]</value>
      <webElementGuid>21dbff73-a16f-4be4-ba06-0e6a9cce249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gurugram'])[1]/preceding::div[1]</value>
      <webElementGuid>9cc67e3d-1d11-449f-979d-d2a7f7b9587c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIND'])[1]/preceding::div[3]</value>
      <webElementGuid>c7d05714-9c95-4c04-b142-b1e636bee2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mumbai']/parent::*</value>
      <webElementGuid>722334e9-cdb5-4cdb-bbd0-7ca9ab98877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]/div/div</value>
      <webElementGuid>59bcaefc-dbd1-4d97-ba00-428f82ac8ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mumbai' or . = 'Mumbai')]</value>
      <webElementGuid>76c754e8-d6fb-4c7a-b2fd-3d3308e50061</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
