<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hyderabad</name>
   <tag></tag>
   <elementGuidId>54fb7dce-7f2f-4521-81e8-d9163d705ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CityCard_stylesdesktop__Container-sc-kme8v3-0.lfNoKp > div.Textstylecommon__Txt-sc-4w6sg8-0.ibvYrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[5]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hyderabad is a melting pot of flavors and aromas Hyderabad&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>063771e7-2a38-4508-9a05-2c2843a43681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>textComponent</value>
      <webElementGuid>29e476cf-34f3-4e67-91f8-038b74362c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#B8B7B7</value>
      <webElementGuid>55df8745-3d7e-49be-85b2-0b63557a9541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>883d2fc8-d532-4efd-b487-45f1d61d7ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>009e18f7-3165-4ae5-8898-f0484fae3ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-style</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>4f9fa9b5-3f7c-4ff9-9bab-ce92976fd60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>28cf8893-dd85-490a-b7b2-6ae1cf767497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>e65176b8-8ac5-4999-a76f-8b43f270bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f13b5109-afed-45e3-aea6-707d85065a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl</value>
      <webElementGuid>bd7b982c-46e6-4f85-98bc-25215c586952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overflow</name>
      <type>Main</type>
      <value>initial</value>
      <webElementGuid>b8d18672-fbb4-4ab3-b643-cf2df28289a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>display</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>a405c8df-d252-4690-88b6-71698ffb2e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hyderabad</value>
      <webElementGuid>816780b8-7c19-4fd5-b9e1-88ec80d4a366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;HomeViewdesktop__Container-sc-1llz785-29 fjeEdZ&quot;]/div[@class=&quot;HomeViewdesktop__HeroSectionWrapper-sc-1llz785-30 fkVtLO&quot;]/div[@class=&quot;HomeViewdesktop__CityCardWrapper-sc-1llz785-33 kHygRA&quot;]/a[5]/div[@class=&quot;CityCard_stylesdesktop__Container-sc-kme8v3-0 lfNoKp&quot;]/div[@class=&quot;Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl&quot;]</value>
      <webElementGuid>1b9c7748-8e1d-4603-b171-1800655fcdeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[5]/div/div</value>
      <webElementGuid>ff13735b-f02d-44ee-9252-954d8d1e0226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pune'])[1]/following::div[2]</value>
      <webElementGuid>ce90c041-d55f-4034-9091-fbe3f20569e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coimbatore'])[1]/following::div[4]</value>
      <webElementGuid>31c9a4e5-0a45-484b-8962-c38145c5f428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noida'])[1]/preceding::div[1]</value>
      <webElementGuid>a1c029ba-b1d2-4aaf-8882-a20c844c24e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delhi'])[1]/preceding::div[3]</value>
      <webElementGuid>90d5532c-4c83-413a-8e7d-ddf9c5d229d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hyderabad']/parent::*</value>
      <webElementGuid>9787fa49-1673-4d2a-b5e7-084409c50fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div/div</value>
      <webElementGuid>5c038150-7424-473a-8d16-54cbe36b216e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hyderabad' or . = 'Hyderabad')]</value>
      <webElementGuid>390f26e8-34b2-4b19-a9da-f82dc2943964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
