<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pune</name>
   <tag></tag>
   <elementGuidId>9576194e-d155-4619-9048-19665fa24539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CityCard_stylesdesktop__Container-sc-kme8v3-0.TocVP > div.Textstylecommon__Txt-sc-4w6sg8-0.ibvYrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Pune is a bustling hub of activity Pune&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e59c5538-d163-4458-97fd-805c4c747578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>textComponent</value>
      <webElementGuid>b81de6b5-65a5-47fa-b84e-2868d92cb921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#B8B7B7</value>
      <webElementGuid>00f1563e-24fe-41bb-8b9d-a1634179dd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>fd49c9ca-65be-44ce-bd0e-34f9a9c98653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>187c9329-5c7c-4805-b5a7-efa1c1655bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-style</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>f3ce6cb5-ad5e-4521-b62b-0abae0e1d87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e5d0db70-f594-4b88-8b43-a65b8f907b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>1f4d3de8-0156-4f95-92a1-82d49a27d198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9a96c4f9-4e1c-48c0-80b9-ea9956f02fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl</value>
      <webElementGuid>392b4b8b-9e3a-4401-8679-eca6e07c52e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overflow</name>
      <type>Main</type>
      <value>initial</value>
      <webElementGuid>5098068f-dffc-4da4-8470-00f0d9ee00df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>display</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>a81c294f-85ae-4530-a9cd-d74f2335125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pune</value>
      <webElementGuid>92e9c158-eee0-4682-8cde-a89a79384176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;HomeViewdesktop__Container-sc-1llz785-29 fjeEdZ&quot;]/div[@class=&quot;HomeViewdesktop__HeroSectionWrapper-sc-1llz785-30 fkVtLO&quot;]/div[@class=&quot;HomeViewdesktop__CityCardWrapper-sc-1llz785-33 kHygRA&quot;]/a[4]/div[@class=&quot;CityCard_stylesdesktop__Container-sc-kme8v3-0 TocVP&quot;]/div[@class=&quot;Textstylecommon__Txt-sc-4w6sg8-0 ibvYrl&quot;]</value>
      <webElementGuid>c6bc7b90-93e0-4efd-ba46-7ccec411d69e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/a[4]/div/div</value>
      <webElementGuid>7c9ed579-531d-4536-adf0-bad641774725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coimbatore'])[1]/following::div[2]</value>
      <webElementGuid>ae38b990-9d98-4dc8-95cf-6c8ff75841d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[1]/following::div[4]</value>
      <webElementGuid>1b37126d-5607-428a-b06f-90c13ef255ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hyderabad'])[1]/preceding::div[1]</value>
      <webElementGuid>9a951e83-f80c-4162-80ab-0c6f082b0f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noida'])[1]/preceding::div[3]</value>
      <webElementGuid>faa01503-1cea-4f63-9bbb-fe293cb8d45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pune']/parent::*</value>
      <webElementGuid>b4516e12-207a-4ff9-80e2-08edc37306c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/div</value>
      <webElementGuid>b9e498ff-9589-4d48-9813-e3793027a397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pune' or . = 'Pune')]</value>
      <webElementGuid>982a7413-eede-460a-aadc-a85414990c5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
