<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Forex</name>
   <tag></tag>
   <elementGuidId>b3bc2d76-166d-4745-a937-cef1c1a30ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/ul/li[7]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Forex&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2bb7b5d-9ba7-4573-a296-df98cf0ccf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1f95z5i-4 drxYQA</value>
      <webElementGuid>12f761ef-84cd-4650-ba24-d120cdc89e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forex</value>
      <webElementGuid>2485b19c-3db8-4e79-97e2-1c3f810c5c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1f95z5i-72 iENbjQ&quot;]/div[@class=&quot;sc-1f95z5i-71 jUwoKe&quot;]/header[@class=&quot;sc-1f95z5i-69 iZbvcb header-sticky&quot;]/ul[@class=&quot;sc-1f95z5i-0 lNqfU&quot;]/li[@class=&quot;sc-1f95z5i-1 hiUlsg&quot;]/a[@class=&quot;sc-1f95z5i-2 hXZcJL&quot;]/span[@class=&quot;sc-1f95z5i-4 drxYQA&quot;]</value>
      <webElementGuid>8ecc4de2-14a3-407c-a4dc-305a118b9bb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/ul/li[7]/a/span[2]</value>
      <webElementGuid>13837888-7ba3-4d12-aadc-39024e3e2699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holidays'])[1]/following::span[2]</value>
      <webElementGuid>8fae4ad8-5226-4a2c-aac5-2e38089b686d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bus'])[1]/following::span[4]</value>
      <webElementGuid>f3fbd5f7-71f5-428d-8088-febbdd8b6d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Your Trips'])[1]/preceding::span[4]</value>
      <webElementGuid>e35ab7f7-d7ae-415a-8483-ee0e252d5bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN / SIGNUP'])[1]/preceding::span[4]</value>
      <webElementGuid>d7935397-51af-4400-a8b7-fecb292084b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forex']/parent::*</value>
      <webElementGuid>0d51c7bc-03f3-4aa9-9ac3-e32a59f27e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span[2]</value>
      <webElementGuid>15a20573-ef87-4662-b81c-cfb456019646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Forex' or . = 'Forex')]</value>
      <webElementGuid>0e7f6434-9156-4023-b568-dedcb7a21932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
