<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DSA</name>
   <tag></tag>
   <elementGuidId>5d7a9bbd-e463-4d7d-bda5-03a7e36a909d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='secondarySubHeader']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#secondarySubHeader >> internal:role=link[name=&quot;DSA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4979b182-0e81-4f46-9311-5bafecf6a94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.geeksforgeeks.org/learn-data-structures-and-algorithms-dsa-tutorial/</value>
      <webElementGuid>72ef677d-5fbd-434e-b2b7-8945f0aa2cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>6b14aab8-89f7-4eb7-bf8c-d37a825b9a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DSA</value>
      <webElementGuid>dc29b79f-e698-4e2a-8d34-c0b769cf2287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondarySubHeader&quot;)/ul[@class=&quot;containerSubheader&quot;]/li[2]/a[@class=&quot;link&quot;]</value>
      <webElementGuid>b330db1b-751c-4ba5-a993-75f1d5bb755a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondarySubHeader']/ul/li[2]/a</value>
      <webElementGuid>4519d0b2-d1fd-422c-9cda-1e9039d1185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'DSA')])[2]</value>
      <webElementGuid>d59e4256-ecc6-40c8-858a-2ac7d7318ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trending Now'])[1]/following::a[1]</value>
      <webElementGuid>34492b98-3626-4adb-9e47-dac51f1e2189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Language'])[1]/following::a[2]</value>
      <webElementGuid>2f91a0fd-2e4d-40d7-a865-7feefff6524e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Tech'])[1]/preceding::a[1]</value>
      <webElementGuid>c1d5036a-8173-4e00-8a24-d7dd11ec9fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foundational Courses'])[1]/preceding::a[2]</value>
      <webElementGuid>4588a1c8-398f-4675-83a2-e86cb9b0c81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DSA']/parent::*</value>
      <webElementGuid>f685e8bf-1857-4149-9165-8cb75f7be1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.geeksforgeeks.org/learn-data-structures-and-algorithms-dsa-tutorial/')])[2]</value>
      <webElementGuid>d8944c47-9f86-43f6-98fa-3dc17ff828ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>9f03e738-d4a6-4799-a4ab-29caf406262a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.geeksforgeeks.org/learn-data-structures-and-algorithms-dsa-tutorial/' and (text() = 'DSA' or . = 'DSA')]</value>
      <webElementGuid>889fd967-ef1f-4bed-aaf0-8ec1d24b8ebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
