<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GATE Courses</name>
   <tag></tag>
   <elementGuidId>e366f218-4be3-4139-913d-84a91c9a8239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topMainHeader']/div/ul/li/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;GATE Courses&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe936f90-8fda-46b7-b1e3-8f22a6140ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.geeksforgeeks.org/courses/category/gate?itm_source=geeksforgeeks&amp;itm_medium=main_header&amp;itm_campaign=courses</value>
      <webElementGuid>cd4eb695-2af4-4545-b870-99f66f387fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner_child</value>
      <webElementGuid>2991f799-57ba-4397-be29-d51a76866b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GATE Courses</value>
      <webElementGuid>defb15f2-c35c-43ba-8748-70c2a9400ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topMainHeader&quot;)/div[@class=&quot;headerContainer&quot;]/ul[@class=&quot;headerMainList&quot;]/li[@class=&quot;headerMainListItem activeNav&quot;]/ul[@class=&quot;megaDropDown  class-0&quot;]/li[@class=&quot;megaDropDownListItem&quot;]/a[@class=&quot;inner_child&quot;]</value>
      <webElementGuid>fbeeb1df-6ed1-4820-8973-39a02e246a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topMainHeader']/div/ul/li/ul/li[3]/a</value>
      <webElementGuid>1d253c8b-dc73-42fb-ba85-be1c46b4ed71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'GATE Courses')]</value>
      <webElementGuid>9d4f25e2-bdac-4dc6-a116-84b2aaad5ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DSA to Development'])[1]/following::a[1]</value>
      <webElementGuid>5bf794c2-9a30-438e-b5fc-f28ffcceac90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GfG Classroom Program'])[1]/following::a[2]</value>
      <webElementGuid>1cfb69a9-d962-4bad-aa70-f491c5e364c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get IBM Certification'])[1]/preceding::a[1]</value>
      <webElementGuid>1178ab6f-c9ed-4e7d-961d-85228cd77707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newly Launched!'])[1]/preceding::a[2]</value>
      <webElementGuid>9054da50-3327-441b-a7b9-f23f065366ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GATE Courses']/parent::*</value>
      <webElementGuid>59c99131-558a-4348-bd33-afde103e9982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.geeksforgeeks.org/courses/category/gate?itm_source=geeksforgeeks&amp;itm_medium=main_header&amp;itm_campaign=courses')]</value>
      <webElementGuid>3c009674-673d-462c-94e6-05ffe7428aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>bfe2a690-c514-40e1-85a2-2466bb60fd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.geeksforgeeks.org/courses/category/gate?itm_source=geeksforgeeks&amp;itm_medium=main_header&amp;itm_campaign=courses' and (text() = 'GATE Courses' or . = 'GATE Courses')]</value>
      <webElementGuid>d379bbc2-9feb-45d4-9d07-9de83603099b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
