<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>55fc3a35-95f7-4d19-a0ff-e2e24f87b9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._3490ry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'All')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;All&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1797372-6614-40e1-8d7a-2be98985ad54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/audio-video/pr?sid=0pm&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_0173a628-adbf-426f-882d-4b17b4dfc336_1_372UD5BXDFYS_MC.9JGNW7M0TUHD&amp;otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Audio~All_9JGNW7M0TUHD&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=9JGNW7M0TUHD</value>
      <webElementGuid>3ccc0d96-e568-489b-ac92-5c8c6cfaf536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3490ry</value>
      <webElementGuid>f9b4dbdf-a7ad-4836-91c1-48f912d63841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>8da46cab-c5ca-4611-b195-947ba0bdbead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[1]/div[@class=&quot;_1UgUYI _2eN8ye&quot;]/div[@class=&quot;_31z7R_&quot;]/object[1]/a[@class=&quot;_3490ry&quot;]</value>
      <webElementGuid>9ca4f1eb-17d8-4bc4-833a-02c064d927ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'All')])[2]</value>
      <webElementGuid>7b10c0a8-be95-4997-ac86-ecd422f22fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tablets'])[1]/following::a[1]</value>
      <webElementGuid>c49b6e12-6178-4ed2-be66-fe86b1cab168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bluetooth Headphones'])[1]/preceding::a[1]</value>
      <webElementGuid>38e38635-09f9-428a-81cd-c4926daf9445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wired Headphones'])[1]/preceding::a[2]</value>
      <webElementGuid>f2c671e6-784a-4f36-a36a-ec44c9431e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>86438dea-910d-472f-b889-ea27c341fa82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/audio-video/pr?sid=0pm&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_0173a628-adbf-426f-882d-4b17b4dfc336_1_372UD5BXDFYS_MC.9JGNW7M0TUHD&amp;otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Audio~All_9JGNW7M0TUHD&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=9JGNW7M0TUHD')]</value>
      <webElementGuid>206a9501-9ac9-423e-80e2-4fb2c57273bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/object/a</value>
      <webElementGuid>89cbbf42-07af-43c0-84bc-45c875d6b07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/audio-video/pr?sid=0pm&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_0173a628-adbf-426f-882d-4b17b4dfc336_1_372UD5BXDFYS_MC.9JGNW7M0TUHD&amp;otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Audio~All_9JGNW7M0TUHD&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=9JGNW7M0TUHD' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>2c8e91d5-9d8a-4633-a457-5c87515d716b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
