<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Headphones Pouch  Case Covers__1wE2Px</name>
   <tag></tag>
   <elementGuidId>81a7d460-1801-4a6d-bca5-4bc022732872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._1wE2Px</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>._1wE2Px</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e37de01d-601a-4d87-bb42-1ab8520889eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1wE2Px</value>
      <webElementGuid>97be6954-50c2-470a-a695-bf44ff902266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[1]/div[@class=&quot;_1wE2Px&quot;]</value>
      <webElementGuid>cfee483a-fa41-4255-8ff0-bd59f82869b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>f24931cb-3a67-437b-9c11-9e8961281f94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
