<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mobiles</name>
   <tag></tag>
   <elementGuidId>ad8bbd9c-e2ce-4a8a-a3a3-f983cc9ece21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/a[2]/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mobiles&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>440be04e-71f5-4012-a7f3-d54499b1f602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobiles</value>
      <webElementGuid>80642d3b-bc60-4d5b-b80a-c8bfcc57b833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;css-175oi2r r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-175oi2r r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;yAlKeh&quot;]/div[@class=&quot;_2L0uxW&quot;]/div[@class=&quot;_3116_u&quot;]/div[@class=&quot;_1yQHx8 _2UnIQ_ _3ak8Rd _2y8Yzt&quot;]/div[1]/div[@class=&quot;css-175oi2r r-13awgt0 r-eqz5dr&quot;]/div[1]/div[1]/div[@class=&quot;_3sdu8W emupdz&quot;]/a[@class=&quot;_1ch8e_&quot;]/div[1]/div[@class=&quot;YBLJE4&quot;]/span[@class=&quot;_1XjE3T&quot;]/span[1]</value>
      <webElementGuid>9d53ee13-b949-4fad-8f1a-7c21c47471f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/a[2]/div/div/span/span</value>
      <webElementGuid>b5b9607f-19a5-4584-a2de-43e08f759bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kilos'])[1]/following::span[2]</value>
      <webElementGuid>9daa9998-575f-4a54-afa8-633ec76cc3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download App'])[1]/following::span[4]</value>
      <webElementGuid>6bc61332-5217-45c9-ab6e-0610cc176510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion'])[1]/preceding::span[1]</value>
      <webElementGuid>1651cedf-1711-4f9e-80e6-0d54f1418329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronics'])[1]/preceding::span[4]</value>
      <webElementGuid>190a6d2d-c42a-4488-8d6e-0f0fd73c4463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobiles']/parent::*</value>
      <webElementGuid>830fd217-3c5c-476c-be22-882234e22261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div/span/span</value>
      <webElementGuid>5cc9fe64-422c-43ef-a28f-96519e0e9a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mobiles' or . = 'Mobiles')]</value>
      <webElementGuid>5cda93ee-260a-49a7-aca2-24e6a990decc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
