<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEARCH</name>
   <tag></tag>
   <elementGuidId>97692872-98a1-4aba-bcff-b3255114b634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.SearchBlockstyles__HswSearchCta-sc-e3pqob-2.jYExik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[3]/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SEARCH&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e432b0fd-6891-4f6f-98c2-63ba3f847bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBlockstyles__HswSearchCta-sc-e3pqob-2 jYExik</value>
      <webElementGuid>87ca685b-6d16-40a1-a9a8-4b550528c0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>b12aa88e-94da-4cd6-b35d-fbdda5248862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;AppOnlineOffline__ContainerOfflineSpan-sc-1p9o9u6-0 cEnHqJ&quot;]/div[@class=&quot;dwebCommonstyles__BaseColumnWrap-sc-112ty3f-2 HomePagestyles__HomeBodyWrapperSection-sc-s8m7jv-0 civGJZ csrQiy&quot;]/div[@class=&quot;HomePagestyles__HomeBodyWrapperContentDiv-sc-s8m7jv-1 ioiaWJ&quot;]/div[@class=&quot;SearchBlockContainerstyles__HContainer-sc-kbckfp-0 itnzki&quot;]/div[@class=&quot;SearchBlockContainerstyles__HContainerInner-sc-kbckfp-1 jpmHVr&quot;]/div[1]/div[@class=&quot;SearchBlockstyles__HSContainer-sc-e3pqob-0 cZzhey&quot;]/div[@class=&quot;SearchBlockstyles__HswSearchCtaCont-sc-e3pqob-1 iobAOu&quot;]/a[@class=&quot;SearchBlockstyles__HswSearchCta-sc-e3pqob-2 jYExik&quot;]</value>
      <webElementGuid>8e69e3b2-b75e-4019-9bdc-269cbd17c416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>d00b27fd-a581-4b81-a467-b5e1f11c5af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEARCH')]</value>
      <webElementGuid>b5fd095f-a092-46b3-b822-45fa21c12289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guests &amp; Rooms'])[1]/following::a[1]</value>
      <webElementGuid>d08e1262-16d7-44f4-aa8b-28652cf58245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-out'])[1]/following::a[1]</value>
      <webElementGuid>adde9253-66c1-4450-a833-13f198b2c426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offers for you'])[1]/preceding::a[1]</value>
      <webElementGuid>fa94054b-5c06-4845-b236-791cad2bfb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>90d0c26e-9a9a-4700-ac76-778716a1daa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>3383ec09-d8c5-468f-8e1d-d6673b364038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>97d807ae-c5a9-4b12-8e82-4407963ff78a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
