<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where to_downshift-1-input</name>
   <tag></tag>
   <elementGuidId>3ffce388-2fbc-4a58-b31b-463d86775ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='downshift-1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g. - Area, Landmark or Property Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b179cb9b-75c7-4d4c-ad33-f4b7321349b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b42a6f9e-f6cf-4154-bea7-a5c06c36a708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>36337d40-2ea7-4b85-abef-e4957a31c461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-1-label</value>
      <webElementGuid>9d2279b6-cdfd-46ee-a848-b492651c1304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>be90aaf3-f279-44de-a0a2-975b8a74cfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-1-input</value>
      <webElementGuid>9822b59f-2801-43ae-9347-d7a9ba85bae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. - Area, Landmark or Property Name</value>
      <webElementGuid>f464819e-2559-4a85-a946-da902e352193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>94eba006-9fe6-4c42-a7df-33290bb88341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-1-menu</value>
      <webElementGuid>2d30b235-a1fe-40e4-9a0a-a05d0dde5824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-1-input&quot;)</value>
      <webElementGuid>476f0f0b-6b49-4b97-b3df-632e789557b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downshift-1-input']</value>
      <webElementGuid>bbf1763a-9de6-4f18-bfee-4288afeb0953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[3]/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>3debd501-fb73-40ce-9388-b85cddd47322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8d2f7209-fa6f-4b55-9eaf-1f1b69300fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'downshift-1-input' and @placeholder = 'e.g. - Area, Landmark or Property Name']</value>
      <webElementGuid>c2d40478-e264-48d9-b330-59f2b832cc9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
