<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Favourite Brands_image-image undefined _95dd02</name>
   <tag></tag>
   <elementGuidId>c09c1f7b-a6ea-4edf-a08b-4ecaaeb064f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/main/div/div[3]/div/div/div/div/div/div/div/div/div/div/a/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image-image.undefined.image-hand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.column-base > .container-base > div > .container-container > .row-base > .column-base > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a619e8c-d5e0-4512-ae61-c309713608c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7780ba2a-1838-4660-b074-0f7817fb9091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-image undefined image-hand</value>
      <webElementGuid>39d26743-d619-45c2-8b6a-d198fe3afbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.myntassets.com/w_108,c_limit,fl_progressive,dpr_2.0/assets/images/2020/11/9/ab69d015-a975-4bda-990c-49e68938f6b31604926460802-19-FavBrands-AllenSollyJuniors.jpg</value>
      <webElementGuid>f8f7d6c6-c7b5-4ba8-88f6-5c02db45708b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[1]/main[@class=&quot;shop-base&quot;]/div[@class=&quot;myx-base&quot;]/div[@class=&quot;myx-indexContainer&quot;]/div[@class=&quot;container-base myx-stretch&quot;]/div[1]/div[@class=&quot;container-container&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;column-base&quot;]/div[@class=&quot;container-base myx-stretch&quot;]/div[1]/div[@class=&quot;container-container container-aspectContainer&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;column-base&quot;]/a[1]/div[1]/picture[@class=&quot;img-responsive&quot;]/img[@class=&quot;image-image undefined image-hand&quot;]</value>
      <webElementGuid>1a5059b6-4109-429f-a25d-8243dff6e836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/main/div/div[3]/div/div/div/div/div/div/div/div/div/div/a/div/picture/img</value>
      <webElementGuid>6d45cf4b-21f6-47ec-aa85-d994c5b11bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.myntassets.com/w_108,c_limit,fl_progressive,dpr_2.0/assets/images/2020/11/9/ab69d015-a975-4bda-990c-49e68938f6b31604926460802-19-FavBrands-AllenSollyJuniors.jpg')]</value>
      <webElementGuid>dff7503a-6c35-4781-a01d-733965b87ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/a/div/picture/img</value>
      <webElementGuid>ec8c1072-2b59-426c-aba9-8516a600c0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.myntassets.com/w_108,c_limit,fl_progressive,dpr_2.0/assets/images/2020/11/9/ab69d015-a975-4bda-990c-49e68938f6b31604926460802-19-FavBrands-AllenSollyJuniors.jpg']</value>
      <webElementGuid>8a3deb05-9d08-4519-a21c-68f311112f20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
