<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gynecologistobstetrician</name>
   <tag></tag>
   <elementGuidId>41605a7e-b708-414e-8f1b-6a8498ac7d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-omni-container']/div/div[2]/div[2]/div/div[2]/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Gynecologist/obstetrician&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7210d53c-dd4c-4eca-a1f2-e35a0c33316c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>omni-suggestion-main</value>
      <webElementGuid>ff97fc79-1de7-46b1-9a7c-64f126b89dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-omni-suggestion-item__content__title</value>
      <webElementGuid>7e77d1ca-5a7a-4727-abde-101a205d3892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gynecologist/obstetrician</value>
      <webElementGuid>99b0dc65-9372-4b2f-a3ba-b89346117628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-omni-container&quot;)/div[@class=&quot;c-omni u-clearfix&quot;]/div[@class=&quot;c-omni__wrapper u-clearfix c-omni__wrapper--keyword&quot;]/div[@class=&quot;c-omni-suggestion-list&quot;]/div[@class=&quot;c-omni-suggestion-group&quot;]/div[@class=&quot;c-omni-suggestion-item&quot;]/span[@class=&quot;c-omni-suggestion-item__content&quot;]/div[@class=&quot;c-omni-suggestion-item__content__title&quot;]</value>
      <webElementGuid>8aa6b258-d5d5-4261-a8f3-1bef177017ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-omni-container']/div/div[2]/div[2]/div/div[2]/span/div</value>
      <webElementGuid>ecb38d20-1cf6-4bc8-b5b6-55d8f98d4bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPECIALITY'])[1]/following::div[4]</value>
      <webElementGuid>7fec8ed3-7540-4fa1-b13e-0285c90ebb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dentist'])[1]/following::div[4]</value>
      <webElementGuid>d90813c5-04e4-476d-ae74-fd88629bd10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPECIALITY'])[2]/preceding::div[1]</value>
      <webElementGuid>ce36f664-16a7-4db1-9a0b-37132772a00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Physician'])[1]/preceding::div[3]</value>
      <webElementGuid>d8d0e70c-d2ec-40cf-a0a5-cc9e5dc2d12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gynecologist/obstetrician']/parent::*</value>
      <webElementGuid>2b3b9a00-bc5e-4cc0-b909-5e56bec05b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div</value>
      <webElementGuid>82fd6d2d-f193-4fe9-a351-d1f14049c839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gynecologist/obstetrician' or . = 'Gynecologist/obstetrician')]</value>
      <webElementGuid>31fd752c-16ec-4828-a8a9-e8953d047ae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
