<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FLAT 25 OFF_btnHoli</name>
   <tag></tag>
   <elementGuidId>2fbc92b6-9c70-439d-b07d-d97cbcf915df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Book Now'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>aside >> internal:has-text=&quot;FLAT 25% OFF* on International Hotels Book Now Book Now&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a70f5ea-d388-4b11-bd73-011e38997ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnHoli</value>
      <webElementGuid>e287252c-db9b-4e9a-9db7-7d23dfed6868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15530b10-e800-4e2c-a52e-12a913db046c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Book Now</value>
      <webElementGuid>70ce02c6-4be8-4cec-8620-9b64f81f32fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hotels&quot;)/div[@class=&quot;pafe&quot;]/div[@class=&quot;item&quot;]/aside[@class=&quot;right&quot;]/div[@class=&quot;flight-section dh_box&quot;]/a[@class=&quot;dshow&quot;]/input[@class=&quot;btnHoli&quot;]</value>
      <webElementGuid>49af1a48-2a27-4160-86b8-cb6885852aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Book Now'])[3]</value>
      <webElementGuid>59632333-d57e-493a-a698-203fa389890a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hotels']/div/div[2]/aside/div[2]/a/input</value>
      <webElementGuid>959f0a39-ad26-4d53-8d3e-4b6b9a5c32c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/aside/div[2]/a/input</value>
      <webElementGuid>802ccee7-a83a-4092-86cc-526c28722498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>f211e677-4fca-4932-9db4-a72be7557a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
