<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_more</name>
   <tag></tag>
   <elementGuidId>1e0531a3-ff9d-4450-945f-2debddd15cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.u-color--primary.u-c-pointer.u-bold.u-smallest-font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-1953257']/div/div/div/div/div[3]/div/div[8]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;more&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c9c12e3-e8c2-4763-a82d-72d22376edd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-color--primary u-c-pointer u-bold u-smallest-font</value>
      <webElementGuid>af4e5f47-a7ed-44db-a055-dfab03b171d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>show_more</value>
      <webElementGuid>96cc408f-40cf-4237-a223-36e03f56012e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more</value>
      <webElementGuid>a22192c2-59bb-40f5-9cba-3fbc7f8be439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-1953257&quot;)/div[@class=&quot;c-profile--sections&quot;]/div[1]/div[1]/div[@class=&quot;pure-g u-cushion-medium u-border--grey-9 u-spacer--top u-spacer--bottom&quot;]/div[@class=&quot;pure-u-1&quot;]/div[@class=&quot;bubbles&quot;]/div[@class=&quot;u-spacer--left u-d-inlineblock&quot;]/span[@class=&quot;u-color--primary u-c-pointer u-bold u-smallest-font&quot;]</value>
      <webElementGuid>8ea5f936-a67c-468f-9cfc-0eeb36e8471e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-1953257']/div/div/div/div/div[3]/div/div[8]/span</value>
      <webElementGuid>a83a6247-b804-4929-8a52-14b025d6c2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. Suryabhan Bhalerao'])[1]/preceding::span[1]</value>
      <webElementGuid>36eac5a4-8cbb-4b22-967d-fea43aef8eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MBBS, MS - General Surgery, DNB - General Surgery'])[1]/preceding::span[1]</value>
      <webElementGuid>6d4179bf-c1c1-40e6-a5e0-44af2eab83b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more']/parent::*</value>
      <webElementGuid>62076412-2f83-4aa2-bf83-f67217cf835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span</value>
      <webElementGuid>727b7be4-c232-481f-bb3c-39d3e1ace831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'more' or . = 'more')]</value>
      <webElementGuid>9d2a0934-d41c-4f5f-9aa7-6b9b4eccd6d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
