<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_specialities</name>
   <tag></tag>
   <elementGuidId>379e452d-0a6f-4880-ba40-18aaf44a9dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-2218879']/div/div[3]/div/div/div[11]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;+ 34 specialities&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db1a3fc5-88c5-4ff0-aa6f-47802ff724ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>specialities</value>
      <webElementGuid>9633cfc3-cac3-469f-a87f-437834060ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-2218879&quot;)/div[1]/div[@class=&quot;u-spacer--top&quot;]/div[@class=&quot;c-profile--sections&quot;]/div[@class=&quot;bubbles&quot;]/div[@class=&quot;u-spacer--left u-d-inlineblock&quot;]/a[@class=&quot;u-color--primary u-c-pointer u-bold u-smallest-font&quot;]/span[1]</value>
      <webElementGuid>9cd631f6-4544-42a8-94a7-2e9be4dcbf59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-2218879']/div/div[3]/div/div/div[11]/a/span</value>
      <webElementGuid>c6a9a275-f641-4bfe-be9f-d44da73608f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctors in'])[1]/preceding::span[1]</value>
      <webElementGuid>3cc16171-0437-4da0-89e0-8e8146f180c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='specialities']/parent::*</value>
      <webElementGuid>ec132865-488d-41d5-b4e1-7f132e5e937e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/a/span</value>
      <webElementGuid>4c3023e6-1983-4268-9262-3bfde108a3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'specialities' or . = 'specialities')]</value>
      <webElementGuid>539760df-d739-4f5d-84dd-4207a344faff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
