<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Copy Link_WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</name>
   <tag></tag>
   <elementGuidId>8bd5cff9-1923-4cf2-8961-0b1768f0822e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='kO001e']/span/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.WpHeLc.VfPpkd-mRLv6.VfPpkd-RLmnJb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Docs&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d4e4a90-17ef-44b6-9351-a18e31990744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</value>
      <webElementGuid>72afbc3e-97d5-439e-976b-2a634606f4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://developers.google.com/speed/docs/insights/v5/about</value>
      <webElementGuid>1c7503e0-64e8-4763-ae3f-35fe64b376b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>05c4d86c-dee9-4cfc-9bc7-c5c0b56bb374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Docs</value>
      <webElementGuid>6e2c063c-5a99-41f5-8a60-9d69e4e694f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>hSRGPd</value>
      <webElementGuid>3fed419f-2488-4e4f-9f80-37b1988a9e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kO001e&quot;)/span[@class=&quot;yTTzpb&quot;]/div[@class=&quot;VfPpkd-dgl2Hf-ppHlrf-sM5MNb&quot;]/div[@class=&quot;VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-dgl2Hf ksBjEc lKxP2d LQeN7 jpGVBd VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d-OWXEXe-AHe6Kc-XpnDCe VfPpkd-ksKsZd-mWPk3d&quot;]/a[@class=&quot;WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb&quot;]</value>
      <webElementGuid>4bbb4cc4-32b6-45f3-b412-11e565617cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='kO001e']/span/div[2]/div/a</value>
      <webElementGuid>193e4a0a-bd80-4b52-aaa7-0b96280cca8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://developers.google.com/speed/docs/insights/v5/about')]</value>
      <webElementGuid>3c00f29c-f7b9-49cb-97d0-19c79b467e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>26b92653-baf2-4b55-b5f0-39c738ab81d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://developers.google.com/speed/docs/insights/v5/about']</value>
      <webElementGuid>22d6bde5-3fc3-41a0-a5ac-708019d05215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
